# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'groupbox_color_bar.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GroupBox_ColorBar(object):
    def setupUi(self, GroupBox_ColorBar):
        GroupBox_ColorBar.setObjectName(_fromUtf8("GroupBox_ColorBar"))
        GroupBox_ColorBar.resize(300, 192)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GroupBox_ColorBar.sizePolicy().hasHeightForWidth())
        GroupBox_ColorBar.setSizePolicy(sizePolicy)
        GroupBox_ColorBar.setCheckable(True)
        GroupBox_ColorBar.setChecked(False)
        self.gridLayout = QtGui.QGridLayout(GroupBox_ColorBar)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalSlider_width = QtGui.QSlider(GroupBox_ColorBar)
        self.horizontalSlider_width.setMaximum(100)
        self.horizontalSlider_width.setProperty("value", 2)
        self.horizontalSlider_width.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_width.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horizontalSlider_width.setTickInterval(10)
        self.horizontalSlider_width.setObjectName(_fromUtf8("horizontalSlider_width"))
        self.gridLayout.addWidget(self.horizontalSlider_width, 4, 2, 1, 1)
        self.label_2 = QtGui.QLabel(GroupBox_ColorBar)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.doubleSpinBox_y = QtGui.QDoubleSpinBox(GroupBox_ColorBar)
        self.doubleSpinBox_y.setMaximum(1.0)
        self.doubleSpinBox_y.setSingleStep(0.1)
        self.doubleSpinBox_y.setProperty("value", 0.05)
        self.doubleSpinBox_y.setObjectName(_fromUtf8("doubleSpinBox_y"))
        self.gridLayout.addWidget(self.doubleSpinBox_y, 3, 3, 1, 1)
        self.horizontalSlider_x = QtGui.QSlider(GroupBox_ColorBar)
        self.horizontalSlider_x.setMaximum(100)
        self.horizontalSlider_x.setProperty("value", 90)
        self.horizontalSlider_x.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_x.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horizontalSlider_x.setTickInterval(10)
        self.horizontalSlider_x.setObjectName(_fromUtf8("horizontalSlider_x"))
        self.gridLayout.addWidget(self.horizontalSlider_x, 2, 2, 1, 1)
        self.horizontalSlider_y = QtGui.QSlider(GroupBox_ColorBar)
        self.horizontalSlider_y.setMaximum(100)
        self.horizontalSlider_y.setProperty("value", 5)
        self.horizontalSlider_y.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_y.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horizontalSlider_y.setTickInterval(10)
        self.horizontalSlider_y.setObjectName(_fromUtf8("horizontalSlider_y"))
        self.gridLayout.addWidget(self.horizontalSlider_y, 3, 2, 1, 1)
        self.label = QtGui.QLabel(GroupBox_ColorBar)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(GroupBox_ColorBar)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_4 = QtGui.QLabel(GroupBox_ColorBar)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.doubleSpinBox_width = QtGui.QDoubleSpinBox(GroupBox_ColorBar)
        self.doubleSpinBox_width.setMaximum(1.0)
        self.doubleSpinBox_width.setSingleStep(0.1)
        self.doubleSpinBox_width.setProperty("value", 0.02)
        self.doubleSpinBox_width.setObjectName(_fromUtf8("doubleSpinBox_width"))
        self.gridLayout.addWidget(self.doubleSpinBox_width, 4, 3, 1, 1)
        self.doubleSpinBox_x = QtGui.QDoubleSpinBox(GroupBox_ColorBar)
        self.doubleSpinBox_x.setMaximum(1.0)
        self.doubleSpinBox_x.setSingleStep(0.1)
        self.doubleSpinBox_x.setProperty("value", 0.9)
        self.doubleSpinBox_x.setObjectName(_fromUtf8("doubleSpinBox_x"))
        self.gridLayout.addWidget(self.doubleSpinBox_x, 2, 3, 1, 1)
        self.comboBox_orientation = QtGui.QComboBox(GroupBox_ColorBar)
        self.comboBox_orientation.setObjectName(_fromUtf8("comboBox_orientation"))
        self.comboBox_orientation.addItem(_fromUtf8(""))
        self.comboBox_orientation.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_orientation, 0, 2, 1, 2)
        self.label_3 = QtGui.QLabel(GroupBox_ColorBar)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_6 = QtGui.QLabel(GroupBox_ColorBar)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.horizontalSlider_height = QtGui.QSlider(GroupBox_ColorBar)
        self.horizontalSlider_height.setMaximum(100)
        self.horizontalSlider_height.setProperty("value", 85)
        self.horizontalSlider_height.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_height.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horizontalSlider_height.setTickInterval(10)
        self.horizontalSlider_height.setObjectName(_fromUtf8("horizontalSlider_height"))
        self.gridLayout.addWidget(self.horizontalSlider_height, 5, 2, 1, 1)
        self.doubleSpinBox_height = QtGui.QDoubleSpinBox(GroupBox_ColorBar)
        self.doubleSpinBox_height.setMaximum(1.0)
        self.doubleSpinBox_height.setSingleStep(0.1)
        self.doubleSpinBox_height.setProperty("value", 0.85)
        self.doubleSpinBox_height.setObjectName(_fromUtf8("doubleSpinBox_height"))
        self.gridLayout.addWidget(self.doubleSpinBox_height, 5, 3, 1, 1)
        self.line = QtGui.QFrame(GroupBox_ColorBar)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 1, 2, 1, 2)
        self.label_2.setBuddy(self.horizontalSlider_x)
        self.label.setBuddy(self.comboBox_orientation)
        self.label_5.setBuddy(self.horizontalSlider_width)
        self.label_3.setBuddy(self.horizontalSlider_y)
        self.label_6.setBuddy(self.horizontalSlider_height)

        self.retranslateUi(GroupBox_ColorBar)
        QtCore.QMetaObject.connectSlotsByName(GroupBox_ColorBar)
        GroupBox_ColorBar.setTabOrder(self.comboBox_orientation, self.horizontalSlider_x)
        GroupBox_ColorBar.setTabOrder(self.horizontalSlider_x, self.doubleSpinBox_x)
        GroupBox_ColorBar.setTabOrder(self.doubleSpinBox_x, self.horizontalSlider_y)
        GroupBox_ColorBar.setTabOrder(self.horizontalSlider_y, self.doubleSpinBox_y)
        GroupBox_ColorBar.setTabOrder(self.doubleSpinBox_y, self.horizontalSlider_width)
        GroupBox_ColorBar.setTabOrder(self.horizontalSlider_width, self.doubleSpinBox_width)
        GroupBox_ColorBar.setTabOrder(self.doubleSpinBox_width, self.horizontalSlider_height)
        GroupBox_ColorBar.setTabOrder(self.horizontalSlider_height, self.doubleSpinBox_height)

    def retranslateUi(self, GroupBox_ColorBar):
        GroupBox_ColorBar.setTitle(_translate("GroupBox_ColorBar", "Color Bar", None))
        self.horizontalSlider_width.setToolTip(_translate("GroupBox_ColorBar", "<html><head/><body><p>width of the color bar</p></body></html>", None))
        self.label_2.setToolTip(_translate("GroupBox_ColorBar", "<html><head/><body><p>lateral position of the left hand corner of the color bar in figure between [0, 1], 0 is the left side.</p></body></html>", None))
        self.label_2.setText(_translate("GroupBox_ColorBar", "X", None))
        self.doubleSpinBox_y.setToolTip(_translate("GroupBox_ColorBar", "<html><head/><body><p>vertical position of the bottom of the color bar in figure between [0, 1], 0 is bottom side.</p></body></html>", None))
        self.horizontalSlider_x.setToolTip(_translate("GroupBox_ColorBar", "<html><head/><body><p>lateral position of the left hand corner of the color bar in figure between [0, 1], 0 is the left side.</p></body></html>", None))
        self.horizontalSlider_y.setToolTip(_translate("GroupBox_ColorBar", "<html><head/><body><p>vertical position of the bottom of the color bar in figure between [0, 1], 0 is bottom side.</p></body></html>", None))
        self.label.setToolTip(_translate("GroupBox_ColorBar", "<html><head/><body><p>orientation of the color bar</p><p><br/></p></body></html>", None))
        self.label.setText(_translate("GroupBox_ColorBar", "Orientation", None))
        self.label_5.setToolTip(_translate("GroupBox_ColorBar", "<html><head/><body><p>width of the color bar</p></body></html>", None))
        self.label_5.setText(_translate("GroupBox_ColorBar", "Width", None))
        self.label_4.setText(_translate("GroupBox_ColorBar", "Position", None))
        self.doubleSpinBox_width.setToolTip(_translate("GroupBox_ColorBar", "<html><head/><body><p>width of the color bar</p></body></html>", None))
        self.doubleSpinBox_x.setToolTip(_translate("GroupBox_ColorBar", "<html><head/><body><p>lateral position of the left hand corner of the color bar in figure between [0, 1], 0 is the left side.</p></body></html>", None))
        self.comboBox_orientation.setToolTip(_translate("GroupBox_ColorBar", "<html><head/><body><p>orientation of the color bar</p><p><br/></p></body></html>", None))
        self.comboBox_orientation.setItemText(0, _translate("GroupBox_ColorBar", "vertical", None))
        self.comboBox_orientation.setItemText(1, _translate("GroupBox_ColorBar", "horizontal", None))
        self.label_3.setToolTip(_translate("GroupBox_ColorBar", "<html><head/><body><p>vertical position of the bottom of the color bar in figure between [0, 1], 0 is bottom side.</p></body></html>", None))
        self.label_3.setText(_translate("GroupBox_ColorBar", "Y", None))
        self.label_6.setToolTip(_translate("GroupBox_ColorBar", "<html><head/><body><p>height of the color bar</p></body></html>", None))
        self.label_6.setText(_translate("GroupBox_ColorBar", "Height", None))
        self.horizontalSlider_height.setToolTip(_translate("GroupBox_ColorBar", "<html><head/><body><p>height of the color bar</p></body></html>", None))
        self.doubleSpinBox_height.setToolTip(_translate("GroupBox_ColorBar", "<html><head/><body><p>height of the color bar</p></body></html>", None))

