# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'groupbox_plot_control_resistivity_phase_pseudo_section.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GroupBox_plot_control_resistivity_phase_pseudo_section(object):
    def setupUi(self, GroupBox_plot_control_resistivity_phase_pseudo_section):
        GroupBox_plot_control_resistivity_phase_pseudo_section.setObjectName(_fromUtf8("GroupBox_plot_control_resistivity_phase_pseudo_section"))
        GroupBox_plot_control_resistivity_phase_pseudo_section.resize(333, 236)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GroupBox_plot_control_resistivity_phase_pseudo_section.sizePolicy().hasHeightForWidth())
        GroupBox_plot_control_resistivity_phase_pseudo_section.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(GroupBox_plot_control_resistivity_phase_pseudo_section)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(GroupBox_plot_control_resistivity_phase_pseudo_section)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.comboBox_phase_cmap = QtGui.QComboBox(GroupBox_plot_control_resistivity_phase_pseudo_section)
        self.comboBox_phase_cmap.setObjectName(_fromUtf8("comboBox_phase_cmap"))
        self.gridLayout.addWidget(self.comboBox_phase_cmap, 2, 2, 1, 1)
        self.label_5 = QtGui.QLabel(GroupBox_plot_control_resistivity_phase_pseudo_section)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(GroupBox_plot_control_resistivity_phase_pseudo_section)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.comboBox_res_cmap = QtGui.QComboBox(GroupBox_plot_control_resistivity_phase_pseudo_section)
        self.comboBox_res_cmap.setEnabled(True)
        self.comboBox_res_cmap.setObjectName(_fromUtf8("comboBox_res_cmap"))
        self.gridLayout.addWidget(self.comboBox_res_cmap, 1, 2, 1, 1)
        self.spinBox_tickspace = QtGui.QSpinBox(GroupBox_plot_control_resistivity_phase_pseudo_section)
        self.spinBox_tickspace.setEnabled(True)
        self.spinBox_tickspace.setProperty("value", 1)
        self.spinBox_tickspace.setObjectName(_fromUtf8("spinBox_tickspace"))
        self.gridLayout.addWidget(self.spinBox_tickspace, 0, 2, 1, 1)
        self.groupBox = QtGui.QGroupBox(GroupBox_plot_control_resistivity_phase_pseudo_section)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.checkBox_zxx = QtGui.QCheckBox(self.groupBox)
        self.checkBox_zxx.setObjectName(_fromUtf8("checkBox_zxx"))
        self.gridLayout_3.addWidget(self.checkBox_zxx, 0, 0, 1, 1)
        self.checkBox_zxy = QtGui.QCheckBox(self.groupBox)
        self.checkBox_zxy.setChecked(True)
        self.checkBox_zxy.setObjectName(_fromUtf8("checkBox_zxy"))
        self.gridLayout_3.addWidget(self.checkBox_zxy, 0, 1, 1, 1)
        self.checkBox_zyx = QtGui.QCheckBox(self.groupBox)
        self.checkBox_zyx.setChecked(True)
        self.checkBox_zyx.setObjectName(_fromUtf8("checkBox_zyx"))
        self.gridLayout_3.addWidget(self.checkBox_zyx, 1, 0, 1, 1)
        self.checkBox_zyy = QtGui.QCheckBox(self.groupBox)
        self.checkBox_zyy.setObjectName(_fromUtf8("checkBox_zyy"))
        self.gridLayout_3.addWidget(self.checkBox_zyy, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 3, 1)
        self.groupBox_limits = QtGui.QGroupBox(GroupBox_plot_control_resistivity_phase_pseudo_section)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_limits.sizePolicy().hasHeightForWidth())
        self.groupBox_limits.setSizePolicy(sizePolicy)
        self.groupBox_limits.setFlat(True)
        self.groupBox_limits.setObjectName(_fromUtf8("groupBox_limits"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_limits)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.doubleSpinBox_res_max = QtGui.QDoubleSpinBox(self.groupBox_limits)
        self.doubleSpinBox_res_max.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_res_max.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_res_max.setSizePolicy(sizePolicy)
        self.doubleSpinBox_res_max.setMaximum(2646.0)
        self.doubleSpinBox_res_max.setProperty("value", 3.0)
        self.doubleSpinBox_res_max.setObjectName(_fromUtf8("doubleSpinBox_res_max"))
        self.gridLayout_2.addWidget(self.doubleSpinBox_res_max, 3, 2, 1, 1)
        self.checkBox_period = QtGui.QCheckBox(self.groupBox_limits)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_period.sizePolicy().hasHeightForWidth())
        self.checkBox_period.setSizePolicy(sizePolicy)
        self.checkBox_period.setObjectName(_fromUtf8("checkBox_period"))
        self.gridLayout_2.addWidget(self.checkBox_period, 2, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_limits)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 2, 1, 1)
        self.doubleSpinBox_phase_max = QtGui.QDoubleSpinBox(self.groupBox_limits)
        self.doubleSpinBox_phase_max.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_phase_max.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_phase_max.setSizePolicy(sizePolicy)
        self.doubleSpinBox_phase_max.setMaximum(360.0)
        self.doubleSpinBox_phase_max.setProperty("value", 90.0)
        self.doubleSpinBox_phase_max.setObjectName(_fromUtf8("doubleSpinBox_phase_max"))
        self.gridLayout_2.addWidget(self.doubleSpinBox_phase_max, 1, 2, 1, 1)
        self.doubleSpinBox_period_max = QtGui.QDoubleSpinBox(self.groupBox_limits)
        self.doubleSpinBox_period_max.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_period_max.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_period_max.setSizePolicy(sizePolicy)
        self.doubleSpinBox_period_max.setSuffix(_fromUtf8(""))
        self.doubleSpinBox_period_max.setMaximum(100.0)
        self.doubleSpinBox_period_max.setObjectName(_fromUtf8("doubleSpinBox_period_max"))
        self.gridLayout_2.addWidget(self.doubleSpinBox_period_max, 2, 2, 1, 1)
        self.checkBox_phase = QtGui.QCheckBox(self.groupBox_limits)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_phase.sizePolicy().hasHeightForWidth())
        self.checkBox_phase.setSizePolicy(sizePolicy)
        self.checkBox_phase.setObjectName(_fromUtf8("checkBox_phase"))
        self.gridLayout_2.addWidget(self.checkBox_phase, 1, 0, 1, 1)
        self.doubleSpinBox_phase_min = QtGui.QDoubleSpinBox(self.groupBox_limits)
        self.doubleSpinBox_phase_min.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_phase_min.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_phase_min.setSizePolicy(sizePolicy)
        self.doubleSpinBox_phase_min.setMaximum(360.0)
        self.doubleSpinBox_phase_min.setObjectName(_fromUtf8("doubleSpinBox_phase_min"))
        self.gridLayout_2.addWidget(self.doubleSpinBox_phase_min, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_limits)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1)
        self.doubleSpinBox_period_min = QtGui.QDoubleSpinBox(self.groupBox_limits)
        self.doubleSpinBox_period_min.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_period_min.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_period_min.setSizePolicy(sizePolicy)
        self.doubleSpinBox_period_min.setSuffix(_fromUtf8(""))
        self.doubleSpinBox_period_min.setMaximum(100.0)
        self.doubleSpinBox_period_min.setObjectName(_fromUtf8("doubleSpinBox_period_min"))
        self.gridLayout_2.addWidget(self.doubleSpinBox_period_min, 2, 1, 1, 1)
        self.checkBox_resistivity = QtGui.QCheckBox(self.groupBox_limits)
        self.checkBox_resistivity.setObjectName(_fromUtf8("checkBox_resistivity"))
        self.gridLayout_2.addWidget(self.checkBox_resistivity, 3, 0, 1, 1)
        self.doubleSpinBox_res_min = QtGui.QDoubleSpinBox(self.groupBox_limits)
        self.doubleSpinBox_res_min.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_res_min.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_res_min.setSizePolicy(sizePolicy)
        self.doubleSpinBox_res_min.setMaximum(2646.0)
        self.doubleSpinBox_res_min.setObjectName(_fromUtf8("doubleSpinBox_res_min"))
        self.gridLayout_2.addWidget(self.doubleSpinBox_res_min, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_limits, 3, 0, 1, 3)
        self.label.setBuddy(self.spinBox_tickspace)

        self.retranslateUi(GroupBox_plot_control_resistivity_phase_pseudo_section)
        QtCore.QMetaObject.connectSlotsByName(GroupBox_plot_control_resistivity_phase_pseudo_section)

    def retranslateUi(self, GroupBox_plot_control_resistivity_phase_pseudo_section):
        GroupBox_plot_control_resistivity_phase_pseudo_section.setWindowTitle(_translate("GroupBox_plot_control_resistivity_phase_pseudo_section", "GroupBox", None))
        GroupBox_plot_control_resistivity_phase_pseudo_section.setTitle(_translate("GroupBox_plot_control_resistivity_phase_pseudo_section", "Plot Settings", None))
        self.label.setToolTip(_translate("GroupBox_plot_control_resistivity_phase_pseudo_section", "<html><head/><body><p>Interger telling at what interval to place station names as the tick labels, in case they are closely spaced</p></body></html>", None))
        self.label.setText(_translate("GroupBox_plot_control_resistivity_phase_pseudo_section", "X Tick Space", None))
        self.label_5.setText(_translate("GroupBox_plot_control_resistivity_phase_pseudo_section", "Phase Colormap", None))
        self.label_2.setText(_translate("GroupBox_plot_control_resistivity_phase_pseudo_section", "Resistivity Colormap", None))
        self.spinBox_tickspace.setToolTip(_translate("GroupBox_plot_control_resistivity_phase_pseudo_section", "<html><head/><body><p>Interger telling at what interval to place station names as the tick labels, in case they are closely spaced</p></body></html>", None))
        self.groupBox.setTitle(_translate("GroupBox_plot_control_resistivity_phase_pseudo_section", "Impedance Components", None))
        self.checkBox_zxx.setText(_translate("GroupBox_plot_control_resistivity_phase_pseudo_section", "ZXX", None))
        self.checkBox_zxy.setText(_translate("GroupBox_plot_control_resistivity_phase_pseudo_section", "ZXY", None))
        self.checkBox_zyx.setText(_translate("GroupBox_plot_control_resistivity_phase_pseudo_section", "ZYX", None))
        self.checkBox_zyy.setText(_translate("GroupBox_plot_control_resistivity_phase_pseudo_section", "ZYY", None))
        self.groupBox_limits.setTitle(_translate("GroupBox_plot_control_resistivity_phase_pseudo_section", "Limits", None))
        self.doubleSpinBox_res_max.setToolTip(_translate("GroupBox_plot_control_resistivity_phase_pseudo_section", "<html><head/><body><p>limits on resistivity in log scale</p></body></html>", None))
        self.checkBox_period.setToolTip(_translate("GroupBox_plot_control_resistivity_phase_pseudo_section", "<html><head/><body><p>limits on th eplotting period in a linear scale</p></body></html>", None))
        self.checkBox_period.setText(_translate("GroupBox_plot_control_resistivity_phase_pseudo_section", "Period", None))
        self.label_4.setText(_translate("GroupBox_plot_control_resistivity_phase_pseudo_section", "Maximum", None))
        self.doubleSpinBox_phase_max.setToolTip(_translate("GroupBox_plot_control_resistivity_phase_pseudo_section", "<html><head/><body><p>minimum and maximum phase in degrees for coloring</p></body></html>", None))
        self.doubleSpinBox_phase_max.setSuffix(_translate("GroupBox_plot_control_resistivity_phase_pseudo_section", "°", None))
        self.doubleSpinBox_period_max.setToolTip(_translate("GroupBox_plot_control_resistivity_phase_pseudo_section", "<html><head/><body><p>limits on th eplotting period in a linear scale</p></body></html>", None))
        self.checkBox_phase.setToolTip(_translate("GroupBox_plot_control_resistivity_phase_pseudo_section", "<html><head/><body><p>minimum and maximum phase in degrees for coloring</p></body></html>", None))
        self.checkBox_phase.setText(_translate("GroupBox_plot_control_resistivity_phase_pseudo_section", "Phase", None))
        self.doubleSpinBox_phase_min.setToolTip(_translate("GroupBox_plot_control_resistivity_phase_pseudo_section", "<html><head/><body><p>minimum and maximum phase in degrees for coloring</p></body></html>", None))
        self.doubleSpinBox_phase_min.setSuffix(_translate("GroupBox_plot_control_resistivity_phase_pseudo_section", "°", None))
        self.label_3.setText(_translate("GroupBox_plot_control_resistivity_phase_pseudo_section", "Minimum", None))
        self.doubleSpinBox_period_min.setToolTip(_translate("GroupBox_plot_control_resistivity_phase_pseudo_section", "<html><head/><body><p>limits on th eplotting period in a linear scale</p></body></html>", None))
        self.checkBox_resistivity.setToolTip(_translate("GroupBox_plot_control_resistivity_phase_pseudo_section", "<html><head/><body><p>limits on resistivity in log scale</p></body></html>", None))
        self.checkBox_resistivity.setText(_translate("GroupBox_plot_control_resistivity_phase_pseudo_section", "Resistivity", None))
        self.doubleSpinBox_res_min.setToolTip(_translate("GroupBox_plot_control_resistivity_phase_pseudo_section", "<html><head/><body><p>limits on resistivity in log scale</p></body></html>", None))

