# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\u64132\Documents\mtpy2\mtpy\gui\SmartMT\ui_asset\plot_parameters.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GroupBoxParameters(object):
    def setupUi(self, GroupBoxParameters):
        GroupBoxParameters.setObjectName(_fromUtf8("GroupBoxParameters"))
        GroupBoxParameters.resize(340, 409)
        self.verticalLayout = QtGui.QVBoxLayout(GroupBoxParameters)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.toolBox = QtGui.QToolBox(GroupBoxParameters)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page_common_settings = QtGui.QWidget()
        self.page_common_settings.setGeometry(QtCore.QRect(0, 0, 320, 322))
        self.page_common_settings.setObjectName(_fromUtf8("page_common_settings"))
        self.verticalLayout_figure = QtGui.QVBoxLayout(self.page_common_settings)
        self.verticalLayout_figure.setObjectName(_fromUtf8("verticalLayout_figure"))
        self.groupBox_title = QtGui.QGroupBox(self.page_common_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_title.sizePolicy().hasHeightForWidth())
        self.groupBox_title.setSizePolicy(sizePolicy)
        self.groupBox_title.setCheckable(True)
        self.groupBox_title.setChecked(False)
        self.groupBox_title.setObjectName(_fromUtf8("groupBox_title"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_title)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalSlider_y = QtGui.QSlider(self.groupBox_title)
        self.horizontalSlider_y.setMaximum(100)
        self.horizontalSlider_y.setProperty("value", 98)
        self.horizontalSlider_y.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_y.setObjectName(_fromUtf8("horizontalSlider_y"))
        self.gridLayout_2.addWidget(self.horizontalSlider_y, 4, 1, 1, 2)
        self.lineEdit_title = QtGui.QLineEdit(self.groupBox_title)
        self.lineEdit_title.setObjectName(_fromUtf8("lineEdit_title"))
        self.gridLayout_2.addWidget(self.lineEdit_title, 0, 1, 1, 3)
        self.doubleSpinBox_x = QtGui.QDoubleSpinBox(self.groupBox_title)
        self.doubleSpinBox_x.setMaximum(1.0)
        self.doubleSpinBox_x.setSingleStep(0.1)
        self.doubleSpinBox_x.setProperty("value", 0.5)
        self.doubleSpinBox_x.setObjectName(_fromUtf8("doubleSpinBox_x"))
        self.gridLayout_2.addWidget(self.doubleSpinBox_x, 3, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_title)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.doubleSpinBox_y = QtGui.QDoubleSpinBox(self.groupBox_title)
        self.doubleSpinBox_y.setMaximum(1.0)
        self.doubleSpinBox_y.setSingleStep(0.1)
        self.doubleSpinBox_y.setProperty("value", 0.98)
        self.doubleSpinBox_y.setObjectName(_fromUtf8("doubleSpinBox_y"))
        self.gridLayout_2.addWidget(self.doubleSpinBox_y, 4, 3, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_title)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_title)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.horizontalSlider_x = QtGui.QSlider(self.groupBox_title)
        self.horizontalSlider_x.setMaximum(100)
        self.horizontalSlider_x.setProperty("value", 50)
        self.horizontalSlider_x.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_x.setObjectName(_fromUtf8("horizontalSlider_x"))
        self.gridLayout_2.addWidget(self.horizontalSlider_x, 3, 1, 1, 2)
        self.label_9 = QtGui.QLabel(self.groupBox_title)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_title)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 6, 0, 1, 2)
        self.comboBox_horizontal_alignment = QtGui.QComboBox(self.groupBox_title)
        self.comboBox_horizontal_alignment.setObjectName(_fromUtf8("comboBox_horizontal_alignment"))
        self.comboBox_horizontal_alignment.addItem(_fromUtf8(""))
        self.comboBox_horizontal_alignment.addItem(_fromUtf8(""))
        self.comboBox_horizontal_alignment.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox_horizontal_alignment, 5, 2, 1, 2)
        self.label_7 = QtGui.QLabel(self.groupBox_title)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 5, 0, 1, 2)
        self.comboBox_vertical_alignment = QtGui.QComboBox(self.groupBox_title)
        self.comboBox_vertical_alignment.setObjectName(_fromUtf8("comboBox_vertical_alignment"))
        self.comboBox_vertical_alignment.addItem(_fromUtf8(""))
        self.comboBox_vertical_alignment.addItem(_fromUtf8(""))
        self.comboBox_vertical_alignment.addItem(_fromUtf8(""))
        self.comboBox_vertical_alignment.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox_vertical_alignment, 6, 2, 1, 2)
        self.spinBox_fontsize = QtGui.QSpinBox(self.groupBox_title)
        self.spinBox_fontsize.setMinimum(4)
        self.spinBox_fontsize.setProperty("value", 12)
        self.spinBox_fontsize.setObjectName(_fromUtf8("spinBox_fontsize"))
        self.gridLayout_2.addWidget(self.spinBox_fontsize, 1, 1, 1, 1)
        self.verticalLayout_figure.addWidget(self.groupBox_title)
        self.groupBox_figure_size = QtGui.QGroupBox(self.page_common_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_figure_size.sizePolicy().hasHeightForWidth())
        self.groupBox_figure_size.setSizePolicy(sizePolicy)
        self.groupBox_figure_size.setCheckable(True)
        self.groupBox_figure_size.setChecked(False)
        self.groupBox_figure_size.setObjectName(_fromUtf8("groupBox_figure_size"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_figure_size)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_figure_size)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_figure_size)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.doubleSpinBox_height_inches = QtGui.QDoubleSpinBox(self.groupBox_figure_size)
        self.doubleSpinBox_height_inches.setMinimum(1.0)
        self.doubleSpinBox_height_inches.setMaximum(1000.0)
        self.doubleSpinBox_height_inches.setProperty("value", 6.0)
        self.doubleSpinBox_height_inches.setObjectName(_fromUtf8("doubleSpinBox_height_inches"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_height_inches, 1, 1, 1, 1)
        self.spinBox_height_pixels = QtGui.QSpinBox(self.groupBox_figure_size)
        self.spinBox_height_pixels.setMinimum(1)
        self.spinBox_height_pixels.setMaximum(1000000)
        self.spinBox_height_pixels.setProperty("value", 600)
        self.spinBox_height_pixels.setObjectName(_fromUtf8("spinBox_height_pixels"))
        self.gridLayout_3.addWidget(self.spinBox_height_pixels, 1, 2, 1, 1)
        self.doubleSpinBox_width_inches = QtGui.QDoubleSpinBox(self.groupBox_figure_size)
        self.doubleSpinBox_width_inches.setMinimum(1.0)
        self.doubleSpinBox_width_inches.setMaximum(1000.0)
        self.doubleSpinBox_width_inches.setProperty("value", 8.0)
        self.doubleSpinBox_width_inches.setObjectName(_fromUtf8("doubleSpinBox_width_inches"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_width_inches, 0, 1, 1, 1)
        self.spinBox_dpi = QtGui.QSpinBox(self.groupBox_figure_size)
        self.spinBox_dpi.setMinimum(1)
        self.spinBox_dpi.setMaximum(1000)
        self.spinBox_dpi.setProperty("value", 80)
        self.spinBox_dpi.setObjectName(_fromUtf8("spinBox_dpi"))
        self.gridLayout_3.addWidget(self.spinBox_dpi, 2, 1, 1, 1)
        self.spinBox_width_pixels = QtGui.QSpinBox(self.groupBox_figure_size)
        self.spinBox_width_pixels.setMinimum(1)
        self.spinBox_width_pixels.setMaximum(1000000)
        self.spinBox_width_pixels.setProperty("value", 800)
        self.spinBox_width_pixels.setObjectName(_fromUtf8("spinBox_width_pixels"))
        self.gridLayout_3.addWidget(self.spinBox_width_pixels, 0, 2, 1, 1)
        self.checkBox_tight_layout = QtGui.QCheckBox(self.groupBox_figure_size)
        self.checkBox_tight_layout.setChecked(True)
        self.checkBox_tight_layout.setObjectName(_fromUtf8("checkBox_tight_layout"))
        self.gridLayout_3.addWidget(self.checkBox_tight_layout, 2, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_figure_size)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.verticalLayout_figure.addWidget(self.groupBox_figure_size)
        self.toolBox.addItem(self.page_common_settings, _fromUtf8(""))
        self.page_plot_parameters = QtGui.QWidget()
        self.page_plot_parameters.setGeometry(QtCore.QRect(0, 0, 320, 322))
        self.page_plot_parameters.setObjectName(_fromUtf8("page_plot_parameters"))
        self.verticalLayout_plot = QtGui.QVBoxLayout(self.page_plot_parameters)
        self.verticalLayout_plot.setMargin(0)
        self.verticalLayout_plot.setObjectName(_fromUtf8("verticalLayout_plot"))
        self.toolBox.addItem(self.page_plot_parameters, _fromUtf8(""))
        self.verticalLayout.addWidget(self.toolBox)

        self.retranslateUi(GroupBoxParameters)
        self.toolBox.setCurrentIndex(1)
        self.comboBox_horizontal_alignment.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(GroupBoxParameters)

    def retranslateUi(self, GroupBoxParameters):
        GroupBoxParameters.setTitle(_translate("GroupBoxParameters", "Plot Configuration", None))
        self.groupBox_title.setTitle(_translate("GroupBoxParameters", "Title", None))
        self.lineEdit_title.setToolTip(_translate("GroupBoxParameters", "<html><head/><body><p>The title of the plot,\n"
"                                               leave blank to\n"
"                                               remove title.</p><p><span style=\" font-weight:600;\">Note:</span>\n"
"                                               The size and location of the title may depends on the selected plot type.</p></body></html>\n"
"                                           ", None))
        self.label_5.setText(_translate("GroupBoxParameters", "X", None))
        self.label.setToolTip(_translate("GroupBoxParameters", "<html><head/><body><p>The title of the plot,\n"
"                                               leave blank to\n"
"                                               remove title.</p><p><span style=\" font-weight:600;\">Note:</span>\n"
"                                               The size and location of the title may depends on the selected plot type.</p></body></html>\n"
"                                           ", None))
        self.label.setText(_translate("GroupBoxParameters", "Plot Title", None))
        self.label_6.setText(_translate("GroupBoxParameters", "Y", None))
        self.label_9.setText(_translate("GroupBoxParameters", "Font Size", None))
        self.label_8.setText(_translate("GroupBoxParameters", "Vertical Alignment", None))
        self.comboBox_horizontal_alignment.setItemText(0, _translate("GroupBoxParameters", "Left", None))
        self.comboBox_horizontal_alignment.setItemText(1, _translate("GroupBoxParameters", "Center", None))
        self.comboBox_horizontal_alignment.setItemText(2, _translate("GroupBoxParameters", "Right", None))
        self.label_7.setText(_translate("GroupBoxParameters", "Horizontal Alignment", None))
        self.comboBox_vertical_alignment.setItemText(0, _translate("GroupBoxParameters", "Top", None))
        self.comboBox_vertical_alignment.setItemText(1, _translate("GroupBoxParameters", "Center", None))
        self.comboBox_vertical_alignment.setItemText(2, _translate("GroupBoxParameters", "Bottom", None))
        self.comboBox_vertical_alignment.setItemText(3, _translate("GroupBoxParameters", "Baseline", None))
        self.spinBox_fontsize.setSuffix(_translate("GroupBoxParameters", "points", None))
        self.groupBox_figure_size.setTitle(_translate("GroupBoxParameters", "Figure Size", None))
        self.label_4.setText(_translate("GroupBoxParameters", "DPI", None))
        self.label_3.setText(_translate("GroupBoxParameters", "Height", None))
        self.doubleSpinBox_height_inches.setSuffix(_translate("GroupBoxParameters", "inches", None))
        self.spinBox_height_pixels.setSuffix(_translate("GroupBoxParameters", "pixels", None))
        self.doubleSpinBox_width_inches.setSuffix(_translate("GroupBoxParameters", "inches", None))
        self.spinBox_width_pixels.setSuffix(_translate("GroupBoxParameters", "pixels", None))
        self.checkBox_tight_layout.setText(_translate("GroupBoxParameters", "Tight Layout", None))
        self.label_2.setText(_translate("GroupBoxParameters", "Width", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_common_settings), _translate("GroupBoxParameters", "Figure Settings", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_plot_parameters), _translate("GroupBoxParameters", "Plot Parameters", None))

