# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\u64132\Documents\mtpy2\mtpy\gui\SmartMT\ui_asset\wizard_export_modem.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Wizard_esport_modem(object):
    def setupUi(self, Wizard_esport_modem):
        Wizard_esport_modem.setObjectName(_fromUtf8("Wizard_esport_modem"))
        Wizard_esport_modem.resize(403, 360)
        self.wizardPage_error_type = QtGui.QWizardPage()
        self.wizardPage_error_type.setObjectName(_fromUtf8("wizardPage_error_type"))
        self.gridLayout_3 = QtGui.QGridLayout(self.wizardPage_error_type)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.wizardPage_error_type)
        self.doubleSpinBox.setMaximum(100.0)
        self.doubleSpinBox.setProperty("value", 5.0)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.gridLayout_3.addWidget(self.doubleSpinBox, 3, 1, 1, 1)
        self.comboBox_error_type = QtGui.QComboBox(self.wizardPage_error_type)
        self.comboBox_error_type.setObjectName(_fromUtf8("comboBox_error_type"))
        self.comboBox_error_type.addItem(_fromUtf8(""))
        self.comboBox_error_type.addItem(_fromUtf8(""))
        self.comboBox_error_type.addItem(_fromUtf8(""))
        self.comboBox_error_type.addItem(_fromUtf8(""))
        self.comboBox_error_type.addItem(_fromUtf8(""))
        self.comboBox_error_type.addItem(_fromUtf8(""))
        self.comboBox_error_type.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.comboBox_error_type, 0, 1, 1, 1)
        self.doubleSpinBox_error_egbert = QtGui.QDoubleSpinBox(self.wizardPage_error_type)
        self.doubleSpinBox_error_egbert.setMaximum(100.0)
        self.doubleSpinBox_error_egbert.setProperty("value", 3.0)
        self.doubleSpinBox_error_egbert.setObjectName(_fromUtf8("doubleSpinBox_error_egbert"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_error_egbert, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.wizardPage_error_type)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.doubleSpinBox_error_floor = QtGui.QDoubleSpinBox(self.wizardPage_error_type)
        self.doubleSpinBox_error_floor.setMaximum(100.0)
        self.doubleSpinBox_error_floor.setProperty("value", 10.0)
        self.doubleSpinBox_error_floor.setObjectName(_fromUtf8("doubleSpinBox_error_floor"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_error_floor, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.wizardPage_error_type)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_error_egbert = QtGui.QLabel(self.wizardPage_error_type)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_error_egbert.sizePolicy().hasHeightForWidth())
        self.label_error_egbert.setSizePolicy(sizePolicy)
        self.label_error_egbert.setObjectName(_fromUtf8("label_error_egbert"))
        self.gridLayout_3.addWidget(self.label_error_egbert, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.wizardPage_error_type)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.wizardPage_error_type)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 4, 0, 1, 1)
        self.doubleSpinBox_error_value = QtGui.QDoubleSpinBox(self.wizardPage_error_type)
        self.doubleSpinBox_error_value.setMaximum(100.0)
        self.doubleSpinBox_error_value.setProperty("value", 5.0)
        self.doubleSpinBox_error_value.setObjectName(_fromUtf8("doubleSpinBox_error_value"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_error_value, 4, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.wizardPage_error_type)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setCheckable(True)
        self.groupBox_3.setChecked(False)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.checkBox_zxx = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_zxx.sizePolicy().hasHeightForWidth())
        self.checkBox_zxx.setSizePolicy(sizePolicy)
        self.checkBox_zxx.setObjectName(_fromUtf8("checkBox_zxx"))
        self.gridLayout_2.addWidget(self.checkBox_zxx, 0, 0, 1, 1)
        self.checkBox_zxy = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_zxy.sizePolicy().hasHeightForWidth())
        self.checkBox_zxy.setSizePolicy(sizePolicy)
        self.checkBox_zxy.setObjectName(_fromUtf8("checkBox_zxy"))
        self.gridLayout_2.addWidget(self.checkBox_zxy, 1, 0, 1, 1)
        self.comboBox_error_type_zxx = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_error_type_zxx.setObjectName(_fromUtf8("comboBox_error_type_zxx"))
        self.comboBox_error_type_zxx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxx.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox_error_type_zxx, 0, 1, 1, 1)
        self.comboBox_error_type_zxy = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_error_type_zxy.setObjectName(_fromUtf8("comboBox_error_type_zxy"))
        self.comboBox_error_type_zxy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxy.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox_error_type_zxy, 1, 1, 1, 1)
        self.comboBox_error_type_zyx = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_error_type_zyx.setObjectName(_fromUtf8("comboBox_error_type_zyx"))
        self.comboBox_error_type_zyx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyx.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox_error_type_zyx, 2, 1, 1, 1)
        self.comboBox_error_type_zyy = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_error_type_zyy.setObjectName(_fromUtf8("comboBox_error_type_zyy"))
        self.comboBox_error_type_zyy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyy.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox_error_type_zyy, 3, 1, 1, 1)
        self.checkBox_zyx = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_zyx.sizePolicy().hasHeightForWidth())
        self.checkBox_zyx.setSizePolicy(sizePolicy)
        self.checkBox_zyx.setObjectName(_fromUtf8("checkBox_zyx"))
        self.gridLayout_2.addWidget(self.checkBox_zyx, 2, 0, 1, 1)
        self.checkBox_zyy = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_zyy.sizePolicy().hasHeightForWidth())
        self.checkBox_zyy.setSizePolicy(sizePolicy)
        self.checkBox_zyy.setObjectName(_fromUtf8("checkBox_zyy"))
        self.gridLayout_2.addWidget(self.checkBox_zyy, 3, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 0, 2, 5, 1)
        Wizard_esport_modem.addPage(self.wizardPage_error_type)
        self.wizardPage2 = QtGui.QWizardPage()
        self.wizardPage2.setObjectName(_fromUtf8("wizardPage2"))
        Wizard_esport_modem.addPage(self.wizardPage2)
        self.label_2.setBuddy(self.doubleSpinBox_error_floor)
        self.label_3.setBuddy(self.doubleSpinBox)
        self.label_error_egbert.setBuddy(self.doubleSpinBox_error_egbert)
        self.label.setBuddy(self.comboBox_error_type)
        self.label_4.setBuddy(self.doubleSpinBox_error_value)

        self.retranslateUi(Wizard_esport_modem)
        self.comboBox_error_type.setCurrentIndex(2)
        self.comboBox_error_type_zxx.setCurrentIndex(2)
        self.comboBox_error_type_zxy.setCurrentIndex(2)
        self.comboBox_error_type_zyx.setCurrentIndex(2)
        self.comboBox_error_type_zyy.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Wizard_esport_modem)

    def retranslateUi(self, Wizard_esport_modem):
        Wizard_esport_modem.setWindowTitle(_translate("Wizard_esport_modem", "Export to ModEM Data File", None))
        self.wizardPage_error_type.setTitle(_translate("Wizard_esport_modem", "Error Type", None))
        self.wizardPage_error_type.setSubTitle(_translate("Wizard_esport_modem", "Error Type(s) of the exported data file. Supported types are floor, value, egbert, egbert (floor), standard deviation, square error, and mean square error. It is also possible to configure error type(s) for each impedance component.   ", None))
        self.doubleSpinBox.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>Absolute tipper error, all tipper error will be set to this value unless you specify error_type as \'floor\' or \'floor_egbert\'. Default is 5%.</p></body></html>", None))
        self.doubleSpinBox.setSuffix(_translate("Wizard_esport_modem", "%", None))
        self.comboBox_error_type.setItemText(0, _translate("Wizard_esport_modem", "floor", None))
        self.comboBox_error_type.setItemText(1, _translate("Wizard_esport_modem", "value", None))
        self.comboBox_error_type.setItemText(2, _translate("Wizard_esport_modem", "egbert", None))
        self.comboBox_error_type.setItemText(3, _translate("Wizard_esport_modem", "egbert (floor)", None))
        self.comboBox_error_type.setItemText(4, _translate("Wizard_esport_modem", "stddev", None))
        self.comboBox_error_type.setItemText(5, _translate("Wizard_esport_modem", "square error", None))
        self.comboBox_error_type.setItemText(6, _translate("Wizard_esport_modem", "mean square error", None))
        self.doubleSpinBox_error_egbert.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>Percentage to multiply sqrt(zxy*zyx) by. Default is 3 precent as prescribed by Egbert &amp; Kelbert.</p></body></html>", None))
        self.doubleSpinBox_error_egbert.setSuffix(_translate("Wizard_esport_modem", "%", None))
        self.label_2.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>Percentage to set the error floor at, anything below this number will be set to this value. Default is 10%</p></body></html>", None))
        self.label_2.setText(_translate("Wizard_esport_modem", "Error Floor", None))
        self.doubleSpinBox_error_floor.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>Percentage to set the error floor at, anything below this number will be set to this value. Default is 10%</p></body></html>", None))
        self.doubleSpinBox_error_floor.setSuffix(_translate("Wizard_esport_modem", "%", None))
        self.label_3.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>Absolute tipper error, all tipper error will be set to this value unless you specify error_type as \'floor\' or \'floor_egbert\'. Default is 5%.</p></body></html>", None))
        self.label_3.setText(_translate("Wizard_esport_modem", "Error Tipper", None))
        self.label_error_egbert.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>Percentage to multiply sqrt(zxy*zyx) by. Default is 3 precent as prescribed by Egbert &amp; Kelbert.</p></body></html>", None))
        self.label_error_egbert.setText(_translate("Wizard_esport_modem", "Error Egbert", None))
        self.label.setText(_translate("Wizard_esport_modem", "Error Type", None))
        self.label_4.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>Percentage to multiply Z by, to set error. Default is 5 for 5% of Z as error.</p></body></html>", None))
        self.label_4.setText(_translate("Wizard_esport_modem", "Error Value", None))
        self.doubleSpinBox_error_value.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>Percentage to multiply Z by, to set error. Default is 5 for 5% of Z as error.</p></body></html>", None))
        self.doubleSpinBox_error_value.setSuffix(_translate("Wizard_esport_modem", "%", None))
        self.groupBox_3.setTitle(_translate("Wizard_esport_modem", "Component Error Type", None))
        self.checkBox_zxx.setText(_translate("Wizard_esport_modem", "zxx", None))
        self.checkBox_zxy.setText(_translate("Wizard_esport_modem", "zxy", None))
        self.comboBox_error_type_zxx.setItemText(0, _translate("Wizard_esport_modem", "floor", None))
        self.comboBox_error_type_zxx.setItemText(1, _translate("Wizard_esport_modem", "value", None))
        self.comboBox_error_type_zxx.setItemText(2, _translate("Wizard_esport_modem", "egbert", None))
        self.comboBox_error_type_zxx.setItemText(3, _translate("Wizard_esport_modem", "egbert (floor)", None))
        self.comboBox_error_type_zxx.setItemText(4, _translate("Wizard_esport_modem", "stddev", None))
        self.comboBox_error_type_zxx.setItemText(5, _translate("Wizard_esport_modem", "square error", None))
        self.comboBox_error_type_zxx.setItemText(6, _translate("Wizard_esport_modem", "mean square error", None))
        self.comboBox_error_type_zxy.setItemText(0, _translate("Wizard_esport_modem", "floor", None))
        self.comboBox_error_type_zxy.setItemText(1, _translate("Wizard_esport_modem", "value", None))
        self.comboBox_error_type_zxy.setItemText(2, _translate("Wizard_esport_modem", "egbert", None))
        self.comboBox_error_type_zxy.setItemText(3, _translate("Wizard_esport_modem", "egbert (floor)", None))
        self.comboBox_error_type_zxy.setItemText(4, _translate("Wizard_esport_modem", "stddev", None))
        self.comboBox_error_type_zxy.setItemText(5, _translate("Wizard_esport_modem", "square error", None))
        self.comboBox_error_type_zxy.setItemText(6, _translate("Wizard_esport_modem", "mean square error", None))
        self.comboBox_error_type_zyx.setItemText(0, _translate("Wizard_esport_modem", "floor", None))
        self.comboBox_error_type_zyx.setItemText(1, _translate("Wizard_esport_modem", "value", None))
        self.comboBox_error_type_zyx.setItemText(2, _translate("Wizard_esport_modem", "egbert", None))
        self.comboBox_error_type_zyx.setItemText(3, _translate("Wizard_esport_modem", "egbert (floor)", None))
        self.comboBox_error_type_zyx.setItemText(4, _translate("Wizard_esport_modem", "stddev", None))
        self.comboBox_error_type_zyx.setItemText(5, _translate("Wizard_esport_modem", "square error", None))
        self.comboBox_error_type_zyx.setItemText(6, _translate("Wizard_esport_modem", "mean square error", None))
        self.comboBox_error_type_zyy.setItemText(0, _translate("Wizard_esport_modem", "floor", None))
        self.comboBox_error_type_zyy.setItemText(1, _translate("Wizard_esport_modem", "value", None))
        self.comboBox_error_type_zyy.setItemText(2, _translate("Wizard_esport_modem", "egbert", None))
        self.comboBox_error_type_zyy.setItemText(3, _translate("Wizard_esport_modem", "egbert (floor)", None))
        self.comboBox_error_type_zyy.setItemText(4, _translate("Wizard_esport_modem", "stddev", None))
        self.comboBox_error_type_zyy.setItemText(5, _translate("Wizard_esport_modem", "square error", None))
        self.comboBox_error_type_zyy.setItemText(6, _translate("Wizard_esport_modem", "mean square error", None))
        self.checkBox_zyx.setText(_translate("Wizard_esport_modem", "zyx", None))
        self.checkBox_zyy.setText(_translate("Wizard_esport_modem", "zyy", None))

