# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\u64132\Documents\mtpy2\mtpy\gui\SmartMT\ui_asset\wizard_export_modem.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Wizard_esport_modem(object):
    def setupUi(self, Wizard_esport_modem):
        Wizard_esport_modem.setObjectName(_fromUtf8("Wizard_esport_modem"))
        Wizard_esport_modem.resize(569, 416)
        Wizard_esport_modem.setWizardStyle(QtGui.QWizard.ModernStyle)
        self.wizardPage_intro = QtGui.QWizardPage()
        self.wizardPage_intro.setObjectName(_fromUtf8("wizardPage_intro"))
        self.gridLayout_4 = QtGui.QGridLayout(self.wizardPage_intro)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        Wizard_esport_modem.addPage(self.wizardPage_intro)
        self.wizardPage_inversion_mode = QtGui.QWizardPage()
        self.wizardPage_inversion_mode.setObjectName(_fromUtf8("wizardPage_inversion_mode"))
        self.gridLayout_7 = QtGui.QGridLayout(self.wizardPage_inversion_mode)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.groupBox = QtGui.QGroupBox(self.wizardPage_inversion_mode)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.radioButton_impedance_full = QtGui.QRadioButton(self.groupBox)
        self.radioButton_impedance_full.setChecked(True)
        self.radioButton_impedance_full.setObjectName(_fromUtf8("radioButton_impedance_full"))
        self.verticalLayout.addWidget(self.radioButton_impedance_full)
        self.radioButton_impedance_off_diagonal = QtGui.QRadioButton(self.groupBox)
        self.radioButton_impedance_off_diagonal.setObjectName(_fromUtf8("radioButton_impedance_off_diagonal"))
        self.verticalLayout.addWidget(self.radioButton_impedance_off_diagonal)
        self.radioButton_impedance_none = QtGui.QRadioButton(self.groupBox)
        self.radioButton_impedance_none.setObjectName(_fromUtf8("radioButton_impedance_none"))
        self.verticalLayout.addWidget(self.radioButton_impedance_none)
        self.gridLayout_7.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.wizardPage_inversion_mode)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.radioButton_vertical_full = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_vertical_full.setChecked(True)
        self.radioButton_vertical_full.setObjectName(_fromUtf8("radioButton_vertical_full"))
        self.verticalLayout_2.addWidget(self.radioButton_vertical_full)
        self.radioButton_vertical_none = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_vertical_none.setObjectName(_fromUtf8("radioButton_vertical_none"))
        self.verticalLayout_2.addWidget(self.radioButton_vertical_none)
        self.gridLayout_7.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_z_unit = QtGui.QGroupBox(self.wizardPage_inversion_mode)
        self.groupBox_z_unit.setObjectName(_fromUtf8("groupBox_z_unit"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_z_unit)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.radioButton_unit_vmt = QtGui.QRadioButton(self.groupBox_z_unit)
        self.radioButton_unit_vmt.setObjectName(_fromUtf8("radioButton_unit_vmt"))
        self.verticalLayout_6.addWidget(self.radioButton_unit_vmt)
        self.radioButton_unit_mvkmnt = QtGui.QRadioButton(self.groupBox_z_unit)
        self.radioButton_unit_mvkmnt.setChecked(True)
        self.radioButton_unit_mvkmnt.setObjectName(_fromUtf8("radioButton_unit_mvkmnt"))
        self.verticalLayout_6.addWidget(self.radioButton_unit_mvkmnt)
        self.radioButton_unit_ohm = QtGui.QRadioButton(self.groupBox_z_unit)
        self.radioButton_unit_ohm.setObjectName(_fromUtf8("radioButton_unit_ohm"))
        self.verticalLayout_6.addWidget(self.radioButton_unit_ohm)
        self.gridLayout_7.addWidget(self.groupBox_z_unit, 1, 1, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.wizardPage_inversion_mode)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_sign_impedance = QtGui.QGroupBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_sign_impedance.sizePolicy().hasHeightForWidth())
        self.groupBox_sign_impedance.setSizePolicy(sizePolicy)
        self.groupBox_sign_impedance.setObjectName(_fromUtf8("groupBox_sign_impedance"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_sign_impedance)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.radioButton_impedance_sign_plus = QtGui.QRadioButton(self.groupBox_sign_impedance)
        self.radioButton_impedance_sign_plus.setChecked(True)
        self.radioButton_impedance_sign_plus.setObjectName(_fromUtf8("radioButton_impedance_sign_plus"))
        self.verticalLayout_4.addWidget(self.radioButton_impedance_sign_plus)
        self.radioButton_impedance_sign_minus = QtGui.QRadioButton(self.groupBox_sign_impedance)
        self.radioButton_impedance_sign_minus.setObjectName(_fromUtf8("radioButton_impedance_sign_minus"))
        self.verticalLayout_4.addWidget(self.radioButton_impedance_sign_minus)
        self.verticalLayout_3.addWidget(self.groupBox_sign_impedance)
        self.groupBox_sign_vertical = QtGui.QGroupBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_sign_vertical.sizePolicy().hasHeightForWidth())
        self.groupBox_sign_vertical.setSizePolicy(sizePolicy)
        self.groupBox_sign_vertical.setObjectName(_fromUtf8("groupBox_sign_vertical"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_sign_vertical)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.radioButton_vertical_sign_plus = QtGui.QRadioButton(self.groupBox_sign_vertical)
        self.radioButton_vertical_sign_plus.setChecked(True)
        self.radioButton_vertical_sign_plus.setObjectName(_fromUtf8("radioButton_vertical_sign_plus"))
        self.verticalLayout_5.addWidget(self.radioButton_vertical_sign_plus)
        self.radioButton_vertical_sign_minus = QtGui.QRadioButton(self.groupBox_sign_vertical)
        self.radioButton_vertical_sign_minus.setObjectName(_fromUtf8("radioButton_vertical_sign_minus"))
        self.verticalLayout_5.addWidget(self.radioButton_vertical_sign_minus)
        self.verticalLayout_3.addWidget(self.groupBox_sign_vertical)
        self.gridLayout_7.addWidget(self.groupBox_4, 1, 0, 1, 1)
        Wizard_esport_modem.addPage(self.wizardPage_inversion_mode)
        self.wizardPage_error_type = QtGui.QWizardPage()
        self.wizardPage_error_type.setObjectName(_fromUtf8("wizardPage_error_type"))
        self.gridLayout_3 = QtGui.QGridLayout(self.wizardPage_error_type)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.doubleSpinBox_error_tipper = QtGui.QDoubleSpinBox(self.wizardPage_error_type)
        self.doubleSpinBox_error_tipper.setMaximum(100.0)
        self.doubleSpinBox_error_tipper.setProperty("value", 5.0)
        self.doubleSpinBox_error_tipper.setObjectName(_fromUtf8("doubleSpinBox_error_tipper"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_error_tipper, 3, 1, 1, 1)
        self.comboBox_error_type = QtGui.QComboBox(self.wizardPage_error_type)
        self.comboBox_error_type.setObjectName(_fromUtf8("comboBox_error_type"))
        self.comboBox_error_type.addItem(_fromUtf8(""))
        self.comboBox_error_type.addItem(_fromUtf8(""))
        self.comboBox_error_type.addItem(_fromUtf8(""))
        self.comboBox_error_type.addItem(_fromUtf8(""))
        self.comboBox_error_type.addItem(_fromUtf8(""))
        self.comboBox_error_type.addItem(_fromUtf8(""))
        self.comboBox_error_type.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.comboBox_error_type, 0, 1, 1, 1)
        self.doubleSpinBox_error_egbert = QtGui.QDoubleSpinBox(self.wizardPage_error_type)
        self.doubleSpinBox_error_egbert.setMaximum(100.0)
        self.doubleSpinBox_error_egbert.setProperty("value", 3.0)
        self.doubleSpinBox_error_egbert.setObjectName(_fromUtf8("doubleSpinBox_error_egbert"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_error_egbert, 1, 1, 1, 1)
        self.label_error_floor = QtGui.QLabel(self.wizardPage_error_type)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_error_floor.sizePolicy().hasHeightForWidth())
        self.label_error_floor.setSizePolicy(sizePolicy)
        self.label_error_floor.setObjectName(_fromUtf8("label_error_floor"))
        self.gridLayout_3.addWidget(self.label_error_floor, 2, 0, 1, 1)
        self.doubleSpinBox_error_floor = QtGui.QDoubleSpinBox(self.wizardPage_error_type)
        self.doubleSpinBox_error_floor.setEnabled(False)
        self.doubleSpinBox_error_floor.setMaximum(100.0)
        self.doubleSpinBox_error_floor.setProperty("value", 10.0)
        self.doubleSpinBox_error_floor.setObjectName(_fromUtf8("doubleSpinBox_error_floor"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_error_floor, 2, 1, 1, 1)
        self.label_error_tipper = QtGui.QLabel(self.wizardPage_error_type)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_error_tipper.sizePolicy().hasHeightForWidth())
        self.label_error_tipper.setSizePolicy(sizePolicy)
        self.label_error_tipper.setObjectName(_fromUtf8("label_error_tipper"))
        self.gridLayout_3.addWidget(self.label_error_tipper, 3, 0, 1, 1)
        self.label_error_egbert = QtGui.QLabel(self.wizardPage_error_type)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_error_egbert.sizePolicy().hasHeightForWidth())
        self.label_error_egbert.setSizePolicy(sizePolicy)
        self.label_error_egbert.setObjectName(_fromUtf8("label_error_egbert"))
        self.gridLayout_3.addWidget(self.label_error_egbert, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.wizardPage_error_type)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_error_value = QtGui.QLabel(self.wizardPage_error_type)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_error_value.sizePolicy().hasHeightForWidth())
        self.label_error_value.setSizePolicy(sizePolicy)
        self.label_error_value.setObjectName(_fromUtf8("label_error_value"))
        self.gridLayout_3.addWidget(self.label_error_value, 4, 0, 1, 1)
        self.doubleSpinBox_error_value = QtGui.QDoubleSpinBox(self.wizardPage_error_type)
        self.doubleSpinBox_error_value.setEnabled(False)
        self.doubleSpinBox_error_value.setMaximum(100.0)
        self.doubleSpinBox_error_value.setProperty("value", 5.0)
        self.doubleSpinBox_error_value.setObjectName(_fromUtf8("doubleSpinBox_error_value"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_error_value, 4, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.wizardPage_error_type)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setChecked(False)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.checkBox_zxx = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_zxx.sizePolicy().hasHeightForWidth())
        self.checkBox_zxx.setSizePolicy(sizePolicy)
        self.checkBox_zxx.setObjectName(_fromUtf8("checkBox_zxx"))
        self.gridLayout_2.addWidget(self.checkBox_zxx, 0, 0, 1, 1)
        self.checkBox_zxy = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_zxy.sizePolicy().hasHeightForWidth())
        self.checkBox_zxy.setSizePolicy(sizePolicy)
        self.checkBox_zxy.setObjectName(_fromUtf8("checkBox_zxy"))
        self.gridLayout_2.addWidget(self.checkBox_zxy, 1, 0, 1, 1)
        self.comboBox_error_type_zxx = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_error_type_zxx.setEnabled(False)
        self.comboBox_error_type_zxx.setObjectName(_fromUtf8("comboBox_error_type_zxx"))
        self.comboBox_error_type_zxx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxx.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox_error_type_zxx, 0, 1, 1, 1)
        self.comboBox_error_type_zxy = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_error_type_zxy.setEnabled(False)
        self.comboBox_error_type_zxy.setObjectName(_fromUtf8("comboBox_error_type_zxy"))
        self.comboBox_error_type_zxy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxy.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox_error_type_zxy, 1, 1, 1, 1)
        self.comboBox_error_type_zyx = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_error_type_zyx.setEnabled(False)
        self.comboBox_error_type_zyx.setObjectName(_fromUtf8("comboBox_error_type_zyx"))
        self.comboBox_error_type_zyx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyx.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox_error_type_zyx, 2, 1, 1, 1)
        self.comboBox_error_type_zyy = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_error_type_zyy.setEnabled(False)
        self.comboBox_error_type_zyy.setObjectName(_fromUtf8("comboBox_error_type_zyy"))
        self.comboBox_error_type_zyy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyy.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox_error_type_zyy, 3, 1, 1, 1)
        self.checkBox_zyx = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_zyx.sizePolicy().hasHeightForWidth())
        self.checkBox_zyx.setSizePolicy(sizePolicy)
        self.checkBox_zyx.setObjectName(_fromUtf8("checkBox_zyx"))
        self.gridLayout_2.addWidget(self.checkBox_zyx, 2, 0, 1, 1)
        self.checkBox_zyy = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_zyy.sizePolicy().hasHeightForWidth())
        self.checkBox_zyy.setSizePolicy(sizePolicy)
        self.checkBox_zyy.setObjectName(_fromUtf8("checkBox_zyy"))
        self.gridLayout_2.addWidget(self.checkBox_zyy, 3, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 0, 2, 5, 1)
        Wizard_esport_modem.addPage(self.wizardPage_error_type)
        self.wizardPage_data = QtGui.QWizardPage()
        self.wizardPage_data.setObjectName(_fromUtf8("wizardPage_data"))
        self.horizontalLayout_data = QtGui.QHBoxLayout(self.wizardPage_data)
        self.horizontalLayout_data.setObjectName(_fromUtf8("horizontalLayout_data"))
        self.groupBox_5 = QtGui.QGroupBox(self.wizardPage_data)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.radioButton_format_1 = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_format_1.setChecked(True)
        self.radioButton_format_1.setObjectName(_fromUtf8("radioButton_format_1"))
        self.verticalLayout_7.addWidget(self.radioButton_format_1)
        self.radioButton_format_2 = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_format_2.setObjectName(_fromUtf8("radioButton_format_2"))
        self.verticalLayout_7.addWidget(self.radioButton_format_2)
        self.horizontalLayout_data.addWidget(self.groupBox_5)
        Wizard_esport_modem.addPage(self.wizardPage_data)
        self.wizardPage_mesh = QtGui.QWizardPage()
        self.wizardPage_mesh.setObjectName(_fromUtf8("wizardPage_mesh"))
        self.gridLayout_mesh = QtGui.QGridLayout(self.wizardPage_mesh)
        self.gridLayout_mesh.setObjectName(_fromUtf8("gridLayout_mesh"))
        self.groupBox_7 = QtGui.QGroupBox(self.wizardPage_mesh)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_7)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox_7)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.doubleSpinBox_cell_size_east = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.doubleSpinBox_cell_size_east.setMaximum(6371000.0)
        self.doubleSpinBox_cell_size_east.setProperty("value", 500.0)
        self.doubleSpinBox_cell_size_east.setObjectName(_fromUtf8("doubleSpinBox_cell_size_east"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_cell_size_east)
        self.label_3 = QtGui.QLabel(self.groupBox_7)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.doubleSpinBox_cell_szie_north = QtGui.QDoubleSpinBox(self.groupBox_7)
        self.doubleSpinBox_cell_szie_north.setMaximum(6371000.0)
        self.doubleSpinBox_cell_szie_north.setProperty("value", 500.0)
        self.doubleSpinBox_cell_szie_north.setObjectName(_fromUtf8("doubleSpinBox_cell_szie_north"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_cell_szie_north)
        self.gridLayout_mesh.addWidget(self.groupBox_7, 0, 0, 1, 1)
        self.groupBox_8 = QtGui.QGroupBox(self.wizardPage_mesh)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_8)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_15 = QtGui.QLabel(self.groupBox_8)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_15)
        self.spinBox_num_layers = QtGui.QSpinBox(self.groupBox_8)
        self.spinBox_num_layers.setMaximum(6471000)
        self.spinBox_num_layers.setProperty("value", 30)
        self.spinBox_num_layers.setObjectName(_fromUtf8("spinBox_num_layers"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinBox_num_layers)
        self.label_16 = QtGui.QLabel(self.groupBox_8)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_16)
        self.spinBox_num_air_layers = QtGui.QSpinBox(self.groupBox_8)
        self.spinBox_num_air_layers.setObjectName(_fromUtf8("spinBox_num_air_layers"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinBox_num_air_layers)
        self.label_12 = QtGui.QLabel(self.groupBox_8)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_12)
        self.doubleSpinBox_z1_thickness = QtGui.QDoubleSpinBox(self.groupBox_8)
        self.doubleSpinBox_z1_thickness.setMaximum(6371000.0)
        self.doubleSpinBox_z1_thickness.setProperty("value", 10.0)
        self.doubleSpinBox_z1_thickness.setObjectName(_fromUtf8("doubleSpinBox_z1_thickness"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_z1_thickness)
        self.label_13 = QtGui.QLabel(self.groupBox_8)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_13)
        self.doubleSpinBox_target_depth = QtGui.QDoubleSpinBox(self.groupBox_8)
        self.doubleSpinBox_target_depth.setMaximum(6371000.0)
        self.doubleSpinBox_target_depth.setProperty("value", 50000.0)
        self.doubleSpinBox_target_depth.setObjectName(_fromUtf8("doubleSpinBox_target_depth"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_target_depth)
        self.label_14 = QtGui.QLabel(self.groupBox_8)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_14)
        self.doubleSpinBox_bottom = QtGui.QDoubleSpinBox(self.groupBox_8)
        self.doubleSpinBox_bottom.setMaximum(6371000.0)
        self.doubleSpinBox_bottom.setProperty("value", 300000.0)
        self.doubleSpinBox_bottom.setObjectName(_fromUtf8("doubleSpinBox_bottom"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_bottom)
        self.gridLayout_mesh.addWidget(self.groupBox_8, 0, 1, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.wizardPage_mesh)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_11 = QtGui.QLabel(self.groupBox_6)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_6.addWidget(self.label_11, 3, 0, 1, 1)
        self.doubleSpinBox_pad_stretch_h = QtGui.QDoubleSpinBox(self.groupBox_6)
        self.doubleSpinBox_pad_stretch_h.setProperty("value", 1.2)
        self.doubleSpinBox_pad_stretch_h.setObjectName(_fromUtf8("doubleSpinBox_pad_stretch_h"))
        self.gridLayout_6.addWidget(self.doubleSpinBox_pad_stretch_h, 3, 1, 1, 1)
        self.spinBox_pad_north = QtGui.QSpinBox(self.groupBox_6)
        self.spinBox_pad_north.setProperty("value", 7)
        self.spinBox_pad_north.setObjectName(_fromUtf8("spinBox_pad_north"))
        self.gridLayout_6.addWidget(self.spinBox_pad_north, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_6.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_6.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_6.addWidget(self.label_5, 1, 0, 1, 1)
        self.spinBox_pad_z = QtGui.QSpinBox(self.groupBox_6)
        self.spinBox_pad_z.setProperty("value", 4)
        self.spinBox_pad_z.setObjectName(_fromUtf8("spinBox_pad_z"))
        self.gridLayout_6.addWidget(self.spinBox_pad_z, 2, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_6)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_6.addWidget(self.label_7, 4, 0, 1, 1)
        self.doubleSpinBox_pad_stretch_v = QtGui.QDoubleSpinBox(self.groupBox_6)
        self.doubleSpinBox_pad_stretch_v.setProperty("value", 1.2)
        self.doubleSpinBox_pad_stretch_v.setObjectName(_fromUtf8("doubleSpinBox_pad_stretch_v"))
        self.gridLayout_6.addWidget(self.doubleSpinBox_pad_stretch_v, 4, 1, 1, 1)
        self.spinBox_pad_east = QtGui.QSpinBox(self.groupBox_6)
        self.spinBox_pad_east.setProperty("value", 7)
        self.spinBox_pad_east.setObjectName(_fromUtf8("spinBox_pad_east"))
        self.gridLayout_6.addWidget(self.spinBox_pad_east, 0, 1, 1, 1)
        self.gridLayout_mesh.addWidget(self.groupBox_6, 1, 0, 1, 1)
        Wizard_esport_modem.addPage(self.wizardPage_mesh)
        self.wizardPage_topography = QtGui.QWizardPage()
        self.wizardPage_topography.setObjectName(_fromUtf8("wizardPage_topography"))
        self.gridLayout = QtGui.QGridLayout(self.wizardPage_topography)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_17 = QtGui.QLabel(self.wizardPage_topography)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 0, 0, 1, 1)
        self.comboBox_topography_file = QtGui.QComboBox(self.wizardPage_topography)
        self.comboBox_topography_file.setEditable(True)
        self.comboBox_topography_file.setObjectName(_fromUtf8("comboBox_topography_file"))
        self.gridLayout.addWidget(self.comboBox_topography_file, 0, 1, 1, 1)
        self.pushButton_browse_topography_file = QtGui.QPushButton(self.wizardPage_topography)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_browse_topography_file.sizePolicy().hasHeightForWidth())
        self.pushButton_browse_topography_file.setSizePolicy(sizePolicy)
        self.pushButton_browse_topography_file.setObjectName(_fromUtf8("pushButton_browse_topography_file"))
        self.gridLayout.addWidget(self.pushButton_browse_topography_file, 0, 2, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox_9 = QtGui.QGroupBox(self.wizardPage_topography)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.radioButton_interpo_method_nearest = QtGui.QRadioButton(self.groupBox_9)
        self.radioButton_interpo_method_nearest.setChecked(True)
        self.radioButton_interpo_method_nearest.setObjectName(_fromUtf8("radioButton_interpo_method_nearest"))
        self.verticalLayout_8.addWidget(self.radioButton_interpo_method_nearest)
        self.radioButton_interpo_method_linear = QtGui.QRadioButton(self.groupBox_9)
        self.radioButton_interpo_method_linear.setObjectName(_fromUtf8("radioButton_interpo_method_linear"))
        self.verticalLayout_8.addWidget(self.radioButton_interpo_method_linear)
        self.radioButton_interpo_method_cubic = QtGui.QRadioButton(self.groupBox_9)
        self.radioButton_interpo_method_cubic.setObjectName(_fromUtf8("radioButton_interpo_method_cubic"))
        self.verticalLayout_8.addWidget(self.radioButton_interpo_method_cubic)
        self.horizontalLayout.addWidget(self.groupBox_9)
        self.groupBox_10 = QtGui.QGroupBox(self.wizardPage_topography)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.formLayout_3 = QtGui.QFormLayout(self.groupBox_10)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_18 = QtGui.QLabel(self.groupBox_10)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_18)
        self.doubleSpinBox_resistivity_air = QtGui.QDoubleSpinBox(self.groupBox_10)
        self.doubleSpinBox_resistivity_air.setDecimals(4)
        self.doubleSpinBox_resistivity_air.setMaximum(2e+17)
        self.doubleSpinBox_resistivity_air.setProperty("value", 1e+17)
        self.doubleSpinBox_resistivity_air.setObjectName(_fromUtf8("doubleSpinBox_resistivity_air"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_resistivity_air)
        self.label_19 = QtGui.QLabel(self.groupBox_10)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_19)
        self.doubleSpinBox_resistivity_sea = QtGui.QDoubleSpinBox(self.groupBox_10)
        self.doubleSpinBox_resistivity_sea.setDecimals(4)
        self.doubleSpinBox_resistivity_sea.setMaximum(2e+20)
        self.doubleSpinBox_resistivity_sea.setObjectName(_fromUtf8("doubleSpinBox_resistivity_sea"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_resistivity_sea)
        self.horizontalLayout.addWidget(self.groupBox_10)
        self.groupBox_11 = QtGui.QGroupBox(self.wizardPage_topography)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.formLayout_4 = QtGui.QFormLayout(self.groupBox_11)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_20 = QtGui.QLabel(self.groupBox_11)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_20)
        self.doubleSpinBox_smoothing_east = QtGui.QDoubleSpinBox(self.groupBox_11)
        self.doubleSpinBox_smoothing_east.setProperty("value", 0.3)
        self.doubleSpinBox_smoothing_east.setObjectName(_fromUtf8("doubleSpinBox_smoothing_east"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_smoothing_east)
        self.label_21 = QtGui.QLabel(self.groupBox_11)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_21)
        self.doubleSpinBox_smoothing_north = QtGui.QDoubleSpinBox(self.groupBox_11)
        self.doubleSpinBox_smoothing_north.setProperty("value", 0.3)
        self.doubleSpinBox_smoothing_north.setObjectName(_fromUtf8("doubleSpinBox_smoothing_north"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_smoothing_north)
        self.label_22 = QtGui.QLabel(self.groupBox_11)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_22)
        self.doubleSpinBox_smoothing_z = QtGui.QDoubleSpinBox(self.groupBox_11)
        self.doubleSpinBox_smoothing_z.setProperty("value", 0.3)
        self.doubleSpinBox_smoothing_z.setObjectName(_fromUtf8("doubleSpinBox_smoothing_z"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_smoothing_z)
        self.label_23 = QtGui.QLabel(self.groupBox_11)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_23)
        self.spinBox_smoothing_number = QtGui.QSpinBox(self.groupBox_11)
        self.spinBox_smoothing_number.setProperty("value", 1)
        self.spinBox_smoothing_number.setObjectName(_fromUtf8("spinBox_smoothing_number"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.spinBox_smoothing_number)
        self.horizontalLayout.addWidget(self.groupBox_11)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 3)
        Wizard_esport_modem.addPage(self.wizardPage_topography)
        self.wizardPage_output = QtGui.QWizardPage()
        self.wizardPage_output.setObjectName(_fromUtf8("wizardPage_output"))
        self.gridLayout_5 = QtGui.QGridLayout(self.wizardPage_output)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.pushButton_browse = QtGui.QPushButton(self.wizardPage_output)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_browse.sizePolicy().hasHeightForWidth())
        self.pushButton_browse.setSizePolicy(sizePolicy)
        self.pushButton_browse.setObjectName(_fromUtf8("pushButton_browse"))
        self.gridLayout_5.addWidget(self.pushButton_browse, 1, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.wizardPage_output)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_5.addWidget(self.label_9, 1, 0, 1, 1)
        self.comboBox_directory = QtGui.QComboBox(self.wizardPage_output)
        self.comboBox_directory.setEditable(True)
        self.comboBox_directory.setObjectName(_fromUtf8("comboBox_directory"))
        self.gridLayout_5.addWidget(self.comboBox_directory, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.wizardPage_output)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_5.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.wizardPage_output)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 2, 0, 1, 3)
        self.lineEdit_full_output = QtGui.QLineEdit(self.wizardPage_output)
        self.lineEdit_full_output.setReadOnly(True)
        self.lineEdit_full_output.setObjectName(_fromUtf8("lineEdit_full_output"))
        self.gridLayout_5.addWidget(self.lineEdit_full_output, 3, 0, 1, 3)
        self.comboBox_output_name = QtGui.QComboBox(self.wizardPage_output)
        self.comboBox_output_name.setEditable(True)
        self.comboBox_output_name.setObjectName(_fromUtf8("comboBox_output_name"))
        self.comboBox_output_name.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.comboBox_output_name, 0, 1, 1, 2)
        Wizard_esport_modem.addPage(self.wizardPage_output)
        self.label_error_floor.setBuddy(self.doubleSpinBox_error_floor)
        self.label_error_tipper.setBuddy(self.doubleSpinBox_error_tipper)
        self.label_error_egbert.setBuddy(self.doubleSpinBox_error_egbert)
        self.label.setBuddy(self.comboBox_error_type)
        self.label_error_value.setBuddy(self.doubleSpinBox_error_value)
        self.label_17.setBuddy(self.comboBox_topography_file)
        self.label_18.setBuddy(self.doubleSpinBox_resistivity_air)
        self.label_19.setBuddy(self.doubleSpinBox_resistivity_sea)
        self.label_20.setBuddy(self.doubleSpinBox_smoothing_east)
        self.label_21.setBuddy(self.doubleSpinBox_smoothing_north)
        self.label_22.setBuddy(self.doubleSpinBox_smoothing_z)
        self.label_23.setBuddy(self.spinBox_smoothing_number)
        self.label_9.setBuddy(self.comboBox_directory)
        self.label_8.setBuddy(self.comboBox_output_name)
        self.label_10.setBuddy(self.lineEdit_full_output)

        self.retranslateUi(Wizard_esport_modem)
        self.comboBox_error_type.setCurrentIndex(2)
        self.comboBox_error_type_zxx.setCurrentIndex(2)
        self.comboBox_error_type_zxy.setCurrentIndex(2)
        self.comboBox_error_type_zyx.setCurrentIndex(2)
        self.comboBox_error_type_zyy.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Wizard_esport_modem)
        Wizard_esport_modem.setTabOrder(self.comboBox_error_type, self.doubleSpinBox_error_egbert)
        Wizard_esport_modem.setTabOrder(self.doubleSpinBox_error_egbert, self.doubleSpinBox_error_floor)
        Wizard_esport_modem.setTabOrder(self.doubleSpinBox_error_floor, self.doubleSpinBox_error_tipper)
        Wizard_esport_modem.setTabOrder(self.doubleSpinBox_error_tipper, self.doubleSpinBox_error_value)
        Wizard_esport_modem.setTabOrder(self.doubleSpinBox_error_value, self.groupBox_3)
        Wizard_esport_modem.setTabOrder(self.groupBox_3, self.checkBox_zxx)
        Wizard_esport_modem.setTabOrder(self.checkBox_zxx, self.comboBox_error_type_zxx)
        Wizard_esport_modem.setTabOrder(self.comboBox_error_type_zxx, self.checkBox_zxy)
        Wizard_esport_modem.setTabOrder(self.checkBox_zxy, self.comboBox_error_type_zxy)
        Wizard_esport_modem.setTabOrder(self.comboBox_error_type_zxy, self.checkBox_zyx)
        Wizard_esport_modem.setTabOrder(self.checkBox_zyx, self.comboBox_error_type_zyx)
        Wizard_esport_modem.setTabOrder(self.comboBox_error_type_zyx, self.checkBox_zyy)
        Wizard_esport_modem.setTabOrder(self.checkBox_zyy, self.comboBox_error_type_zyy)

    def retranslateUi(self, Wizard_esport_modem):
        Wizard_esport_modem.setWindowTitle(_translate("Wizard_esport_modem", "Export to ModEM Data File", None))
        self.wizardPage_intro.setTitle(_translate("Wizard_esport_modem", "Introduction", None))
        self.wizardPage_intro.setSubTitle(_translate("Wizard_esport_modem", "This wizard will help you to export the selected stations to the ModEM data files.", None))
        self.wizardPage_inversion_mode.setTitle(_translate("Wizard_esport_modem", "Inversion Mode", None))
        self.groupBox.setTitle(_translate("Wizard_esport_modem", "Impedance Components", None))
        self.radioButton_impedance_full.setToolTip(
            _translate("Wizard_esport_modem", "<html><head/><body><p>zxx, zxy, zyx, and zyy</p></body></html>", None))
        self.radioButton_impedance_full.setText(_translate("Wizard_esport_modem", "All", None))
        self.radioButton_impedance_off_diagonal.setToolTip(
            _translate("Wizard_esport_modem", "<html><head/><body><p>zxy and zyx</p></body></html>", None))
        self.radioButton_impedance_off_diagonal.setText(_translate("Wizard_esport_modem", "Off Diagonal", None))
        self.radioButton_impedance_none.setText(_translate("Wizard_esport_modem", "None", None))
        self.groupBox_2.setTitle(_translate("Wizard_esport_modem", "Vertical Components", None))
        self.radioButton_vertical_full.setToolTip(
            _translate("Wizard_esport_modem", "<html><head/><body><p>tx and ty</p></body></html>", None))
        self.radioButton_vertical_full.setText(_translate("Wizard_esport_modem", "All", None))
        self.radioButton_vertical_none.setText(_translate("Wizard_esport_modem", "None", None))
        self.groupBox_z_unit.setToolTip(
            _translate("Wizard_esport_modem", "<html><head/><body><p>Units of Z</p></body></html>", None))
        self.groupBox_z_unit.setTitle(_translate("Wizard_esport_modem", "Z-Unit", None))
        self.radioButton_unit_vmt.setText(_translate("Wizard_esport_modem", "[V/m]/[T]", None))
        self.radioButton_unit_mvkmnt.setText(_translate("Wizard_esport_modem", "[mV/km]/[nT]", None))
        self.radioButton_unit_ohm.setText(_translate("Wizard_esport_modem", "Ohm", None))
        self.groupBox_4.setToolTip(
            _translate("Wizard_esport_modem", "<html><head/><body><p>Sign of time depend wave. Default is \'+\'\n"
                                              "                             as positive downwards.</p></body></html>\n"
                                              "                         ", None))
        self.groupBox_4.setTitle(_translate("Wizard_esport_modem", "Wave Sign", None))
        self.groupBox_sign_impedance.setTitle(_translate("Wizard_esport_modem", "Impedances", None))
        self.radioButton_impedance_sign_plus.setText(_translate("Wizard_esport_modem", "+", None))
        self.radioButton_impedance_sign_minus.setText(_translate("Wizard_esport_modem", "-", None))
        self.groupBox_sign_vertical.setTitle(_translate("Wizard_esport_modem", "Vertical/Tipper", None))
        self.radioButton_vertical_sign_plus.setText(_translate("Wizard_esport_modem", "+", None))
        self.radioButton_vertical_sign_minus.setText(_translate("Wizard_esport_modem", "-", None))
        self.wizardPage_error_type.setTitle(_translate("Wizard_esport_modem", "Error Type", None))
        self.wizardPage_error_type.setSubTitle(_translate("Wizard_esport_modem", "Error Type(s) of the exported data file. Supported types are floor, value, egbert, egbert (floor), standard deviation, square error, and mean square error. It is also possible to configure error type(s) for each impedance component.   ", None))
        self.doubleSpinBox_error_tipper.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>Absolute tipper error, all tipper error will be set to this value unless you specify error_type as \'floor\' or \'floor_egbert\'. Default is 5%.</p></body></html>", None))
        self.doubleSpinBox_error_tipper.setSuffix(_translate("Wizard_esport_modem", "%", None))
        self.comboBox_error_type.setItemText(0, _translate("Wizard_esport_modem", "floor", None))
        self.comboBox_error_type.setItemText(1, _translate("Wizard_esport_modem", "value", None))
        self.comboBox_error_type.setItemText(2, _translate("Wizard_esport_modem", "egbert", None))
        self.comboBox_error_type.setItemText(3, _translate("Wizard_esport_modem", "egbert (floor)", None))
        self.comboBox_error_type.setItemText(4, _translate("Wizard_esport_modem", "stddev", None))
        self.comboBox_error_type.setItemText(5, _translate("Wizard_esport_modem", "square error", None))
        self.comboBox_error_type.setItemText(6, _translate("Wizard_esport_modem", "mean square error", None))
        self.doubleSpinBox_error_egbert.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>Percentage to multiply sqrt(zxy*zyx) by. Default is 3 precent as prescribed by Egbert &amp; Kelbert.</p></body></html>", None))
        self.doubleSpinBox_error_egbert.setSuffix(_translate("Wizard_esport_modem", "%", None))
        self.label_error_floor.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>Percentage to set the error floor at, anything below this number will be set to this value. Default is 10%</p></body></html>", None))
        self.label_error_floor.setText(_translate("Wizard_esport_modem", "Error Floor", None))
        self.doubleSpinBox_error_floor.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>Percentage to set the error floor at, anything below this number will be set to this value. Default is 10%</p></body></html>", None))
        self.doubleSpinBox_error_floor.setSuffix(_translate("Wizard_esport_modem", "%", None))
        self.label_error_tipper.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>Absolute tipper error, all tipper error will be set to this value unless you specify error_type as \'floor\' or \'floor_egbert\'. Default is 5%.</p></body></html>", None))
        self.label_error_tipper.setText(_translate("Wizard_esport_modem", "Error Tipper", None))
        self.label_error_egbert.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>Percentage to multiply sqrt(zxy*zyx) by. Default is 3 precent as prescribed by Egbert &amp; Kelbert.</p></body></html>", None))
        self.label_error_egbert.setText(_translate("Wizard_esport_modem", "Error Egbert", None))
        self.label.setText(_translate("Wizard_esport_modem", "Error Type", None))
        self.label_error_value.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>Percentage to multiply Z by, to set error. Default is 5 for 5% of Z as error.</p></body></html>", None))
        self.label_error_value.setText(_translate("Wizard_esport_modem", "Error Value", None))
        self.doubleSpinBox_error_value.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>Percentage to multiply Z by, to set error. Default is 5 for 5% of Z as error.</p></body></html>", None))
        self.doubleSpinBox_error_value.setSuffix(_translate("Wizard_esport_modem", "%", None))
        self.groupBox_3.setTitle(_translate("Wizard_esport_modem", "Component Error Type", None))
        self.checkBox_zxx.setText(_translate("Wizard_esport_modem", "zxx", None))
        self.checkBox_zxy.setText(_translate("Wizard_esport_modem", "zxy", None))
        self.comboBox_error_type_zxx.setItemText(0, _translate("Wizard_esport_modem", "floor", None))
        self.comboBox_error_type_zxx.setItemText(1, _translate("Wizard_esport_modem", "value", None))
        self.comboBox_error_type_zxx.setItemText(2, _translate("Wizard_esport_modem", "egbert", None))
        self.comboBox_error_type_zxx.setItemText(3, _translate("Wizard_esport_modem", "egbert (floor)", None))
        self.comboBox_error_type_zxx.setItemText(4, _translate("Wizard_esport_modem", "stddev", None))
        self.comboBox_error_type_zxx.setItemText(5, _translate("Wizard_esport_modem", "square error", None))
        self.comboBox_error_type_zxx.setItemText(6, _translate("Wizard_esport_modem", "mean square error", None))
        self.comboBox_error_type_zxy.setItemText(0, _translate("Wizard_esport_modem", "floor", None))
        self.comboBox_error_type_zxy.setItemText(1, _translate("Wizard_esport_modem", "value", None))
        self.comboBox_error_type_zxy.setItemText(2, _translate("Wizard_esport_modem", "egbert", None))
        self.comboBox_error_type_zxy.setItemText(3, _translate("Wizard_esport_modem", "egbert (floor)", None))
        self.comboBox_error_type_zxy.setItemText(4, _translate("Wizard_esport_modem", "stddev", None))
        self.comboBox_error_type_zxy.setItemText(5, _translate("Wizard_esport_modem", "square error", None))
        self.comboBox_error_type_zxy.setItemText(6, _translate("Wizard_esport_modem", "mean square error", None))
        self.comboBox_error_type_zyx.setItemText(0, _translate("Wizard_esport_modem", "floor", None))
        self.comboBox_error_type_zyx.setItemText(1, _translate("Wizard_esport_modem", "value", None))
        self.comboBox_error_type_zyx.setItemText(2, _translate("Wizard_esport_modem", "egbert", None))
        self.comboBox_error_type_zyx.setItemText(3, _translate("Wizard_esport_modem", "egbert (floor)", None))
        self.comboBox_error_type_zyx.setItemText(4, _translate("Wizard_esport_modem", "stddev", None))
        self.comboBox_error_type_zyx.setItemText(5, _translate("Wizard_esport_modem", "square error", None))
        self.comboBox_error_type_zyx.setItemText(6, _translate("Wizard_esport_modem", "mean square error", None))
        self.comboBox_error_type_zyy.setItemText(0, _translate("Wizard_esport_modem", "floor", None))
        self.comboBox_error_type_zyy.setItemText(1, _translate("Wizard_esport_modem", "value", None))
        self.comboBox_error_type_zyy.setItemText(2, _translate("Wizard_esport_modem", "egbert", None))
        self.comboBox_error_type_zyy.setItemText(3, _translate("Wizard_esport_modem", "egbert (floor)", None))
        self.comboBox_error_type_zyy.setItemText(4, _translate("Wizard_esport_modem", "stddev", None))
        self.comboBox_error_type_zyy.setItemText(5, _translate("Wizard_esport_modem", "square error", None))
        self.comboBox_error_type_zyy.setItemText(6, _translate("Wizard_esport_modem", "mean square error", None))
        self.checkBox_zyx.setText(_translate("Wizard_esport_modem", "zyx", None))
        self.checkBox_zyy.setText(_translate("Wizard_esport_modem", "zyy", None))
        self.wizardPage_data.setTitle(_translate("Wizard_esport_modem", "Other Data Settings", None))
        self.groupBox_5.setTitle(_translate("Wizard_esport_modem", "Data File Format", None))
        self.radioButton_format_1.setText(_translate("Wizard_esport_modem", "Type 1", None))
        self.radioButton_format_2.setText(_translate("Wizard_esport_modem", "Type 2", None))
        self.wizardPage_mesh.setTitle(_translate("Wizard_esport_modem", "Mesh Settings", None))
        self.groupBox_7.setTitle(_translate("Wizard_esport_modem", "Horizontal Plane", None))
        self.label_2.setToolTip(
            _translate("Wizard_esport_modem", "<html><head/><body><p>mesh block width in east-west\n"
                                              "                                         direction</p></body></html>\n"
                                              "                                     ", None))
        self.label_2.setText(_translate("Wizard_esport_modem", "Cell Size East", None))
        self.doubleSpinBox_cell_size_east.setToolTip(
            _translate("Wizard_esport_modem", "<html><head/><body><p>mesh block width in east-west\n"
                                              "                                         direction</p></body></html>\n"
                                              "                                     ", None))
        self.doubleSpinBox_cell_size_east.setSuffix(_translate("Wizard_esport_modem", "m", None))
        self.label_3.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>mesh block width in north\n"
                                                                  "                                         direction</p></body></html>\n"
                                                                  "                                     ", None))
        self.label_3.setText(_translate("Wizard_esport_modem", "Cell Size North", None))
        self.doubleSpinBox_cell_szie_north.setToolTip(
            _translate("Wizard_esport_modem", "<html><head/><body><p>mesh block width in north\n"
                                              "                                         direction</p></body></html>\n"
                                              "                                     ", None))
        self.doubleSpinBox_cell_szie_north.setSuffix(_translate("Wizard_esport_modem", "m", None))
        self.groupBox_8.setTitle(_translate("Wizard_esport_modem", "Vertical", None))
        self.label_15.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>total number of vertical\n"
                                                                   "                                         layers in the model</p></body></html>\n"
                                                                   "                                     ", None))
        self.label_15.setText(_translate("Wizard_esport_modem", "Number of Layers", None))
        self.spinBox_num_layers.setToolTip(
            _translate("Wizard_esport_modem", "<html><head/><body><p>total number of vertical\n"
                                              "                                         layers in the model</p></body></html>\n"
                                              "                                     ", None))
        self.label_16.setToolTip(
            _translate("Wizard_esport_modem", "<html><head/><body><p>number of air layers</p></body></html>", None))
        self.label_16.setText(_translate("Wizard_esport_modem", "Number of Air Layers", None))
        self.spinBox_num_air_layers.setToolTip(
            _translate("Wizard_esport_modem", "<html><head/><body><p>number of air layers</p></body></html>", None))
        self.label_12.setToolTip(
            _translate("Wizard_esport_modem", "<html><head/><body><p>thickness of the first layer</p></body></html>",
                       None))
        self.label_12.setText(_translate("Wizard_esport_modem", "First Layer Thickness", None))
        self.doubleSpinBox_z1_thickness.setToolTip(
            _translate("Wizard_esport_modem", "<html><head/><body><p>thickness of the first layer</p></body></html>",
                       None))
        self.doubleSpinBox_z1_thickness.setSuffix(_translate("Wizard_esport_modem", "m", None))
        self.label_13.setToolTip(
            _translate("Wizard_esport_modem", "<html><head/><body><p>depth of deepest target</p></body></html>", None))
        self.label_13.setText(_translate("Wizard_esport_modem", "Target Depth", None))
        self.doubleSpinBox_target_depth.setToolTip(
            _translate("Wizard_esport_modem", "<html><head/><body><p>depth of deepest target</p></body></html>", None))
        self.doubleSpinBox_target_depth.setSuffix(_translate("Wizard_esport_modem", "m", None))
        self.label_14.setToolTip(
            _translate("Wizard_esport_modem", "<html><head/><body><p>absolute bottom of the model</p></body></html>",
                       None))
        self.label_14.setText(_translate("Wizard_esport_modem", "Bottom", None))
        self.doubleSpinBox_bottom.setToolTip(
            _translate("Wizard_esport_modem", "<html><head/><body><p>absolute bottom of the model</p></body></html>",
                       None))
        self.groupBox_6.setTitle(_translate("Wizard_esport_modem", "Paddings", None))
        self.label_11.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>factor to increase by in\n"
                                                                   "                                         padding cells (vertical)</p></body></html>\n"
                                                                   "                                     ", None))
        self.label_11.setText(_translate("Wizard_esport_modem", "Horizontal Stretch", None))
        self.doubleSpinBox_pad_stretch_h.setToolTip(
            _translate("Wizard_esport_modem", "<html><head/><body><p>factor to increase by in\n"
                                              "                                         padding cells (vertical)</p></body></html>\n"
                                              "                                     ", None))
        self.spinBox_pad_north.setToolTip(
            _translate("Wizard_esport_modem", "<html><head/><body><p>number of padding cells on\n"
                                              "                                         the North and South directions</p></body></html>\n"
                                              "                                     ", None))
        self.spinBox_pad_north.setSuffix(_translate("Wizard_esport_modem", "cells", None))
        self.label_4.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>Number of padding cells on\n"
                                                                  "                                         East and West directions</p></body></html>\n"
                                                                  "                                     ", None))
        self.label_4.setText(_translate("Wizard_esport_modem", "East and West", None))
        self.label_6.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>number of vertical padding\n"
                                                                  "                                         cells</p></body></html>\n"
                                                                  "                                     ", None))
        self.label_6.setText(_translate("Wizard_esport_modem", "Bottom", None))
        self.label_5.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>number of padding cells on\n"
                                                                  "                                         the North and South directions</p></body></html>\n"
                                                                  "                                     ", None))
        self.label_5.setText(_translate("Wizard_esport_modem", "North and South", None))
        self.spinBox_pad_z.setToolTip(
            _translate("Wizard_esport_modem", "<html><head/><body><p>number of vertical padding\n"
                                              "                                         cells</p></body></html>\n"
                                              "                                     ", None))
        self.spinBox_pad_z.setSuffix(_translate("Wizard_esport_modem", "cells", None))
        self.label_7.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>factor to increase by in\n"
                                                                  "                                         padding cells (horizontal)</p></body></html>\n"
                                                                  "                                     ", None))
        self.label_7.setText(_translate("Wizard_esport_modem", "Vertical Stretch", None))
        self.doubleSpinBox_pad_stretch_v.setToolTip(
            _translate("Wizard_esport_modem", "<html><head/><body><p>factor to increase by in\n"
                                              "                                         padding cells (horizontal)</p></body></html>\n"
                                              "                                     ", None))
        self.spinBox_pad_east.setToolTip(
            _translate("Wizard_esport_modem", "<html><head/><body><p>Number of padding cells on\n"
                                              "                                         East and West directions</p></body></html>\n"
                                              "                                     ", None))
        self.spinBox_pad_east.setSuffix(_translate("Wizard_esport_modem", "cells", None))
        self.wizardPage_topography.setTitle(_translate("Wizard_esport_modem", "Topography", None))
        self.wizardPage_topography.setSubTitle(_translate("Wizard_esport_modem",
                                                          "After creating the mesh grid, the topography file is used to define resistivity model.",
                                                          None))
        self.label_17.setText(_translate("Wizard_esport_modem", "Fopography File", None))
        self.comboBox_topography_file.setToolTip(
            _translate("Wizard_esport_modem", "<html><head/><body><p>Directory to save the file</p></body></html>",
                       None))
        self.pushButton_browse_topography_file.setToolTip(
            _translate("Wizard_esport_modem", "<html><head/><body><p>Directory to save the file</p></body></html>",
                       None))
        self.pushButton_browse_topography_file.setText(_translate("Wizard_esport_modem", "Browse", None))
        self.groupBox_9.setToolTip(_translate("Wizard_esport_modem",
                                              "<html><head/><body><p>default is \'nearest\', if model grid is dense compared to the surface points then choose \'linear\' or \'cubic\'</p></body></html>",
                                              None))
        self.groupBox_9.setTitle(_translate("Wizard_esport_modem", "Interpolation Method", None))
        self.radioButton_interpo_method_nearest.setText(_translate("Wizard_esport_modem", "Nearest", None))
        self.radioButton_interpo_method_linear.setText(_translate("Wizard_esport_modem", "Linear", None))
        self.radioButton_interpo_method_cubic.setText(_translate("Wizard_esport_modem", "Cubic", None))
        self.groupBox_10.setTitle(_translate("Wizard_esport_modem", "Default Resistivity", None))
        self.label_18.setText(_translate("Wizard_esport_modem", "Air", None))
        self.label_19.setText(_translate("Wizard_esport_modem", "Sea", None))
        self.groupBox_11.setTitle(_translate("Wizard_esport_modem", "Smoothing", None))
        self.label_20.setText(_translate("Wizard_esport_modem", "East", None))
        self.label_21.setText(_translate("Wizard_esport_modem", "North", None))
        self.label_22.setText(_translate("Wizard_esport_modem", "Z", None))
        self.label_23.setText(_translate("Wizard_esport_modem", "Number", None))
        self.wizardPage_output.setTitle(_translate("Wizard_esport_modem", "Output", None))
        self.wizardPage_output.setSubTitle(_translate("Wizard_esport_modem",
                                                      "Plsease select the output directry and the new folder that will be created to save all the data\n"
                                                      "                 files for ModEM.\n"
                                                      "             ", None))
        self.pushButton_browse.setToolTip(
            _translate("Wizard_esport_modem", "<html><head/><body><p>Directory to save the file</p></body></html>",
                       None))
        self.pushButton_browse.setText(_translate("Wizard_esport_modem", "Browse", None))
        self.label_9.setText(_translate("Wizard_esport_modem", "Output Directory", None))
        self.comboBox_directory.setToolTip(
            _translate("Wizard_esport_modem", "<html><head/><body><p>Directory to save the file</p></body></html>",
                       None))
        self.label_8.setText(_translate("Wizard_esport_modem", "Output Name", None))
        self.label_10.setText(_translate("Wizard_esport_modem", "All data files will be written to:", None))
        self.comboBox_output_name.setToolTip(
            _translate("Wizard_esport_modem", "<html><head/><body><p>Name of the image file (with or without .\n"
                                              "                             format extension)</p></body></html>\n"
                                              "                         ", None))
        self.comboBox_output_name.setItemText(0, _translate("Wizard_esport_modem", "ModEM_data", None))

