# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\u64132\Documents\mtpy2\mtpy\gui\SmartMT\ui_asset\wizard_export_modem.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Wizard_esport_modem(object):
    def setupUi(self, Wizard_esport_modem):
        Wizard_esport_modem.setObjectName(_fromUtf8("Wizard_esport_modem"))
        Wizard_esport_modem.resize(403, 374)
        self.wizardPage_intro = QtGui.QWizardPage()
        self.wizardPage_intro.setObjectName(_fromUtf8("wizardPage_intro"))
        self.gridLayout_4 = QtGui.QGridLayout(self.wizardPage_intro)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_5 = QtGui.QLabel(self.wizardPage_intro)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.wizardPage_intro)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 3, 0, 1, 2)
        self.pushButton_browse = QtGui.QPushButton(self.wizardPage_intro)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_browse.sizePolicy().hasHeightForWidth())
        self.pushButton_browse.setSizePolicy(sizePolicy)
        self.pushButton_browse.setObjectName(_fromUtf8("pushButton_browse"))
        self.gridLayout_4.addWidget(self.pushButton_browse, 2, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.wizardPage_intro)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 1, 0, 2, 1)
        self.comboBox_output_name = QtGui.QComboBox(self.wizardPage_intro)
        self.comboBox_output_name.setEditable(True)
        self.comboBox_output_name.setObjectName(_fromUtf8("comboBox_output_name"))
        self.comboBox_output_name.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.comboBox_output_name, 0, 1, 1, 2)
        self.comboBox_directory = QtGui.QComboBox(self.wizardPage_intro)
        self.comboBox_directory.setEditable(True)
        self.comboBox_directory.setObjectName(_fromUtf8("comboBox_directory"))
        self.gridLayout_4.addWidget(self.comboBox_directory, 2, 1, 1, 1)
        self.lineEdit_full_output = QtGui.QLineEdit(self.wizardPage_intro)
        self.lineEdit_full_output.setReadOnly(True)
        self.lineEdit_full_output.setObjectName(_fromUtf8("lineEdit_full_output"))
        self.gridLayout_4.addWidget(self.lineEdit_full_output, 4, 0, 1, 3)
        Wizard_esport_modem.addPage(self.wizardPage_intro)
        self.wizardPage_inversion_mode = QtGui.QWizardPage()
        self.wizardPage_inversion_mode.setObjectName(_fromUtf8("wizardPage_inversion_mode"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.wizardPage_inversion_mode)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox = QtGui.QGroupBox(self.wizardPage_inversion_mode)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.radioButton_impedance_full = QtGui.QRadioButton(self.groupBox)
        self.radioButton_impedance_full.setChecked(True)
        self.radioButton_impedance_full.setObjectName(_fromUtf8("radioButton_impedance_full"))
        self.verticalLayout.addWidget(self.radioButton_impedance_full)
        self.radioButton_impedance_off_diagonal = QtGui.QRadioButton(self.groupBox)
        self.radioButton_impedance_off_diagonal.setObjectName(_fromUtf8("radioButton_impedance_off_diagonal"))
        self.verticalLayout.addWidget(self.radioButton_impedance_off_diagonal)
        self.radioButton_impedance_none = QtGui.QRadioButton(self.groupBox)
        self.radioButton_impedance_none.setObjectName(_fromUtf8("radioButton_impedance_none"))
        self.verticalLayout.addWidget(self.radioButton_impedance_none)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.wizardPage_inversion_mode)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.radioButton_vertical_full = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_vertical_full.setChecked(True)
        self.radioButton_vertical_full.setObjectName(_fromUtf8("radioButton_vertical_full"))
        self.verticalLayout_2.addWidget(self.radioButton_vertical_full)
        self.radioButton_vertical_none = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_vertical_none.setObjectName(_fromUtf8("radioButton_vertical_none"))
        self.verticalLayout_2.addWidget(self.radioButton_vertical_none)
        self.horizontalLayout.addWidget(self.groupBox_2)
        Wizard_esport_modem.addPage(self.wizardPage_inversion_mode)
        self.wizardPage_error_type = QtGui.QWizardPage()
        self.wizardPage_error_type.setObjectName(_fromUtf8("wizardPage_error_type"))
        self.gridLayout_3 = QtGui.QGridLayout(self.wizardPage_error_type)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.doubleSpinBox_error_tipper = QtGui.QDoubleSpinBox(self.wizardPage_error_type)
        self.doubleSpinBox_error_tipper.setMaximum(100.0)
        self.doubleSpinBox_error_tipper.setProperty("value", 5.0)
        self.doubleSpinBox_error_tipper.setObjectName(_fromUtf8("doubleSpinBox_error_tipper"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_error_tipper, 3, 1, 1, 1)
        self.comboBox_error_type = QtGui.QComboBox(self.wizardPage_error_type)
        self.comboBox_error_type.setObjectName(_fromUtf8("comboBox_error_type"))
        self.comboBox_error_type.addItem(_fromUtf8(""))
        self.comboBox_error_type.addItem(_fromUtf8(""))
        self.comboBox_error_type.addItem(_fromUtf8(""))
        self.comboBox_error_type.addItem(_fromUtf8(""))
        self.comboBox_error_type.addItem(_fromUtf8(""))
        self.comboBox_error_type.addItem(_fromUtf8(""))
        self.comboBox_error_type.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.comboBox_error_type, 0, 1, 1, 1)
        self.doubleSpinBox_error_egbert = QtGui.QDoubleSpinBox(self.wizardPage_error_type)
        self.doubleSpinBox_error_egbert.setMaximum(100.0)
        self.doubleSpinBox_error_egbert.setProperty("value", 3.0)
        self.doubleSpinBox_error_egbert.setObjectName(_fromUtf8("doubleSpinBox_error_egbert"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_error_egbert, 1, 1, 1, 1)
        self.label_error_floor = QtGui.QLabel(self.wizardPage_error_type)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_error_floor.sizePolicy().hasHeightForWidth())
        self.label_error_floor.setSizePolicy(sizePolicy)
        self.label_error_floor.setObjectName(_fromUtf8("label_error_floor"))
        self.gridLayout_3.addWidget(self.label_error_floor, 2, 0, 1, 1)
        self.doubleSpinBox_error_floor = QtGui.QDoubleSpinBox(self.wizardPage_error_type)
        self.doubleSpinBox_error_floor.setEnabled(False)
        self.doubleSpinBox_error_floor.setMaximum(100.0)
        self.doubleSpinBox_error_floor.setProperty("value", 10.0)
        self.doubleSpinBox_error_floor.setObjectName(_fromUtf8("doubleSpinBox_error_floor"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_error_floor, 2, 1, 1, 1)
        self.label_error_tipper = QtGui.QLabel(self.wizardPage_error_type)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_error_tipper.sizePolicy().hasHeightForWidth())
        self.label_error_tipper.setSizePolicy(sizePolicy)
        self.label_error_tipper.setObjectName(_fromUtf8("label_error_tipper"))
        self.gridLayout_3.addWidget(self.label_error_tipper, 3, 0, 1, 1)
        self.label_error_egbert = QtGui.QLabel(self.wizardPage_error_type)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_error_egbert.sizePolicy().hasHeightForWidth())
        self.label_error_egbert.setSizePolicy(sizePolicy)
        self.label_error_egbert.setObjectName(_fromUtf8("label_error_egbert"))
        self.gridLayout_3.addWidget(self.label_error_egbert, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.wizardPage_error_type)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_error_value = QtGui.QLabel(self.wizardPage_error_type)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_error_value.sizePolicy().hasHeightForWidth())
        self.label_error_value.setSizePolicy(sizePolicy)
        self.label_error_value.setObjectName(_fromUtf8("label_error_value"))
        self.gridLayout_3.addWidget(self.label_error_value, 4, 0, 1, 1)
        self.doubleSpinBox_error_value = QtGui.QDoubleSpinBox(self.wizardPage_error_type)
        self.doubleSpinBox_error_value.setEnabled(False)
        self.doubleSpinBox_error_value.setMaximum(100.0)
        self.doubleSpinBox_error_value.setProperty("value", 5.0)
        self.doubleSpinBox_error_value.setObjectName(_fromUtf8("doubleSpinBox_error_value"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_error_value, 4, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.wizardPage_error_type)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setChecked(False)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.checkBox_zxx = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_zxx.sizePolicy().hasHeightForWidth())
        self.checkBox_zxx.setSizePolicy(sizePolicy)
        self.checkBox_zxx.setObjectName(_fromUtf8("checkBox_zxx"))
        self.gridLayout_2.addWidget(self.checkBox_zxx, 0, 0, 1, 1)
        self.checkBox_zxy = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_zxy.sizePolicy().hasHeightForWidth())
        self.checkBox_zxy.setSizePolicy(sizePolicy)
        self.checkBox_zxy.setObjectName(_fromUtf8("checkBox_zxy"))
        self.gridLayout_2.addWidget(self.checkBox_zxy, 1, 0, 1, 1)
        self.comboBox_error_type_zxx = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_error_type_zxx.setEnabled(False)
        self.comboBox_error_type_zxx.setObjectName(_fromUtf8("comboBox_error_type_zxx"))
        self.comboBox_error_type_zxx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxx.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox_error_type_zxx, 0, 1, 1, 1)
        self.comboBox_error_type_zxy = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_error_type_zxy.setEnabled(False)
        self.comboBox_error_type_zxy.setObjectName(_fromUtf8("comboBox_error_type_zxy"))
        self.comboBox_error_type_zxy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zxy.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox_error_type_zxy, 1, 1, 1, 1)
        self.comboBox_error_type_zyx = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_error_type_zyx.setEnabled(False)
        self.comboBox_error_type_zyx.setObjectName(_fromUtf8("comboBox_error_type_zyx"))
        self.comboBox_error_type_zyx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyx.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyx.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox_error_type_zyx, 2, 1, 1, 1)
        self.comboBox_error_type_zyy = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_error_type_zyy.setEnabled(False)
        self.comboBox_error_type_zyy.setObjectName(_fromUtf8("comboBox_error_type_zyy"))
        self.comboBox_error_type_zyy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyy.addItem(_fromUtf8(""))
        self.comboBox_error_type_zyy.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox_error_type_zyy, 3, 1, 1, 1)
        self.checkBox_zyx = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_zyx.sizePolicy().hasHeightForWidth())
        self.checkBox_zyx.setSizePolicy(sizePolicy)
        self.checkBox_zyx.setObjectName(_fromUtf8("checkBox_zyx"))
        self.gridLayout_2.addWidget(self.checkBox_zyx, 2, 0, 1, 1)
        self.checkBox_zyy = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_zyy.sizePolicy().hasHeightForWidth())
        self.checkBox_zyy.setSizePolicy(sizePolicy)
        self.checkBox_zyy.setObjectName(_fromUtf8("checkBox_zyy"))
        self.gridLayout_2.addWidget(self.checkBox_zyy, 3, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 0, 2, 5, 1)
        Wizard_esport_modem.addPage(self.wizardPage_error_type)
        self.wizardPage_wave_sign_unit = QtGui.QWizardPage()
        self.wizardPage_wave_sign_unit.setObjectName(_fromUtf8("wizardPage_wave_sign_unit"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.wizardPage_wave_sign_unit)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox_4 = QtGui.QGroupBox(self.wizardPage_wave_sign_unit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_sign_impedance = QtGui.QGroupBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_sign_impedance.sizePolicy().hasHeightForWidth())
        self.groupBox_sign_impedance.setSizePolicy(sizePolicy)
        self.groupBox_sign_impedance.setObjectName(_fromUtf8("groupBox_sign_impedance"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_sign_impedance)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.radioButton_impedance_sign_plus = QtGui.QRadioButton(self.groupBox_sign_impedance)
        self.radioButton_impedance_sign_plus.setChecked(True)
        self.radioButton_impedance_sign_plus.setObjectName(_fromUtf8("radioButton_impedance_sign_plus"))
        self.verticalLayout_4.addWidget(self.radioButton_impedance_sign_plus)
        self.radioButton_impedance_sign_minus = QtGui.QRadioButton(self.groupBox_sign_impedance)
        self.radioButton_impedance_sign_minus.setObjectName(_fromUtf8("radioButton_impedance_sign_minus"))
        self.verticalLayout_4.addWidget(self.radioButton_impedance_sign_minus)
        self.verticalLayout_3.addWidget(self.groupBox_sign_impedance)
        self.groupBox_sign_vertical = QtGui.QGroupBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_sign_vertical.sizePolicy().hasHeightForWidth())
        self.groupBox_sign_vertical.setSizePolicy(sizePolicy)
        self.groupBox_sign_vertical.setObjectName(_fromUtf8("groupBox_sign_vertical"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_sign_vertical)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.radioButton_vertical_sign_plus = QtGui.QRadioButton(self.groupBox_sign_vertical)
        self.radioButton_vertical_sign_plus.setChecked(True)
        self.radioButton_vertical_sign_plus.setObjectName(_fromUtf8("radioButton_vertical_sign_plus"))
        self.verticalLayout_5.addWidget(self.radioButton_vertical_sign_plus)
        self.radioButton_vertical_sign_minus = QtGui.QRadioButton(self.groupBox_sign_vertical)
        self.radioButton_vertical_sign_minus.setObjectName(_fromUtf8("radioButton_vertical_sign_minus"))
        self.verticalLayout_5.addWidget(self.radioButton_vertical_sign_minus)
        self.verticalLayout_3.addWidget(self.groupBox_sign_vertical)
        self.horizontalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_z_unit = QtGui.QGroupBox(self.wizardPage_wave_sign_unit)
        self.groupBox_z_unit.setObjectName(_fromUtf8("groupBox_z_unit"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_z_unit)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.radioButton_unit_vmt = QtGui.QRadioButton(self.groupBox_z_unit)
        self.radioButton_unit_vmt.setObjectName(_fromUtf8("radioButton_unit_vmt"))
        self.verticalLayout_6.addWidget(self.radioButton_unit_vmt)
        self.radioButton_unit_mvkmnt = QtGui.QRadioButton(self.groupBox_z_unit)
        self.radioButton_unit_mvkmnt.setChecked(True)
        self.radioButton_unit_mvkmnt.setObjectName(_fromUtf8("radioButton_unit_mvkmnt"))
        self.verticalLayout_6.addWidget(self.radioButton_unit_mvkmnt)
        self.radioButton_unit_ohm = QtGui.QRadioButton(self.groupBox_z_unit)
        self.radioButton_unit_ohm.setObjectName(_fromUtf8("radioButton_unit_ohm"))
        self.verticalLayout_6.addWidget(self.radioButton_unit_ohm)
        self.horizontalLayout_2.addWidget(self.groupBox_z_unit)
        Wizard_esport_modem.addPage(self.wizardPage_wave_sign_unit)
        self.wizardPage_data = QtGui.QWizardPage()
        self.wizardPage_data.setObjectName(_fromUtf8("wizardPage_data"))
        self.horizontalLayout_data = QtGui.QHBoxLayout(self.wizardPage_data)
        self.horizontalLayout_data.setObjectName(_fromUtf8("horizontalLayout_data"))
        self.groupBox_5 = QtGui.QGroupBox(self.wizardPage_data)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.radioButton_format_2 = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_format_2.setObjectName(_fromUtf8("radioButton_format_2"))
        self.verticalLayout_7.addWidget(self.radioButton_format_2)
        self.radioButton_format_1 = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_format_1.setChecked(True)
        self.radioButton_format_1.setObjectName(_fromUtf8("radioButton_format_1"))
        self.verticalLayout_7.addWidget(self.radioButton_format_1)
        self.horizontalLayout_data.addWidget(self.groupBox_5)
        Wizard_esport_modem.addPage(self.wizardPage_data)
        self.label_5.setBuddy(self.comboBox_output_name)
        self.label_7.setBuddy(self.lineEdit_full_output)
        self.label_6.setBuddy(self.comboBox_directory)
        self.label_error_floor.setBuddy(self.doubleSpinBox_error_floor)
        self.label_error_tipper.setBuddy(self.doubleSpinBox_error_tipper)
        self.label_error_egbert.setBuddy(self.doubleSpinBox_error_egbert)
        self.label.setBuddy(self.comboBox_error_type)
        self.label_error_value.setBuddy(self.doubleSpinBox_error_value)

        self.retranslateUi(Wizard_esport_modem)
        self.comboBox_error_type.setCurrentIndex(2)
        self.comboBox_error_type_zxx.setCurrentIndex(2)
        self.comboBox_error_type_zxy.setCurrentIndex(2)
        self.comboBox_error_type_zyx.setCurrentIndex(2)
        self.comboBox_error_type_zyy.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Wizard_esport_modem)
        Wizard_esport_modem.setTabOrder(self.comboBox_output_name, self.comboBox_directory)
        Wizard_esport_modem.setTabOrder(self.comboBox_directory, self.pushButton_browse)
        Wizard_esport_modem.setTabOrder(self.pushButton_browse, self.comboBox_error_type)
        Wizard_esport_modem.setTabOrder(self.comboBox_error_type, self.doubleSpinBox_error_egbert)
        Wizard_esport_modem.setTabOrder(self.doubleSpinBox_error_egbert, self.doubleSpinBox_error_floor)
        Wizard_esport_modem.setTabOrder(self.doubleSpinBox_error_floor, self.doubleSpinBox_error_tipper)
        Wizard_esport_modem.setTabOrder(self.doubleSpinBox_error_tipper, self.doubleSpinBox_error_value)
        Wizard_esport_modem.setTabOrder(self.doubleSpinBox_error_value, self.groupBox_3)
        Wizard_esport_modem.setTabOrder(self.groupBox_3, self.checkBox_zxx)
        Wizard_esport_modem.setTabOrder(self.checkBox_zxx, self.comboBox_error_type_zxx)
        Wizard_esport_modem.setTabOrder(self.comboBox_error_type_zxx, self.checkBox_zxy)
        Wizard_esport_modem.setTabOrder(self.checkBox_zxy, self.comboBox_error_type_zxy)
        Wizard_esport_modem.setTabOrder(self.comboBox_error_type_zxy, self.checkBox_zyx)
        Wizard_esport_modem.setTabOrder(self.checkBox_zyx, self.comboBox_error_type_zyx)
        Wizard_esport_modem.setTabOrder(self.comboBox_error_type_zyx, self.checkBox_zyy)
        Wizard_esport_modem.setTabOrder(self.checkBox_zyy, self.comboBox_error_type_zyy)

    def retranslateUi(self, Wizard_esport_modem):
        Wizard_esport_modem.setWindowTitle(_translate("Wizard_esport_modem", "Export to ModEM Data File", None))
        self.wizardPage_intro.setTitle(_translate("Wizard_esport_modem", "Introduction", None))
        self.wizardPage_intro.setSubTitle(_translate("Wizard_esport_modem", "This wizard will help you to export the selected stations to the ModEM data files.", None))
        self.label_5.setText(_translate("Wizard_esport_modem", "Output Name", None))
        self.label_7.setText(_translate("Wizard_esport_modem", "All data files will be written to:", None))
        self.pushButton_browse.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>Directory to save the file</p></body></html>", None))
        self.pushButton_browse.setText(_translate("Wizard_esport_modem", "Browse", None))
        self.label_6.setText(_translate("Wizard_esport_modem", "Output Directory", None))
        self.comboBox_output_name.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>Name of the image file (with or without . format extension)</p></body></html>", None))
        self.comboBox_output_name.setItemText(0, _translate("Wizard_esport_modem", "ModEM_data", None))
        self.comboBox_directory.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>Directory to save the file</p></body></html>", None))
        self.wizardPage_inversion_mode.setTitle(_translate("Wizard_esport_modem", "Inversion Mode", None))
        self.groupBox.setTitle(_translate("Wizard_esport_modem", "Impedance Components", None))
        self.radioButton_impedance_full.setToolTip(
            _translate("Wizard_esport_modem", "<html><head/><body><p>zxx, zxy, zyx, and zyy</p></body></html>", None))
        self.radioButton_impedance_full.setText(_translate("Wizard_esport_modem", "All", None))
        self.radioButton_impedance_off_diagonal.setToolTip(
            _translate("Wizard_esport_modem", "<html><head/><body><p>zxy and zyx</p></body></html>", None))
        self.radioButton_impedance_off_diagonal.setText(_translate("Wizard_esport_modem", "Off Diagonal", None))
        self.radioButton_impedance_none.setText(_translate("Wizard_esport_modem", "None", None))
        self.groupBox_2.setTitle(_translate("Wizard_esport_modem", "Vertical Components", None))
        self.radioButton_vertical_full.setToolTip(
            _translate("Wizard_esport_modem", "<html><head/><body><p>tx and ty</p></body></html>", None))
        self.radioButton_vertical_full.setText(_translate("Wizard_esport_modem", "All", None))
        self.radioButton_vertical_none.setText(_translate("Wizard_esport_modem", "None", None))
        self.wizardPage_error_type.setTitle(_translate("Wizard_esport_modem", "Error Type", None))
        self.wizardPage_error_type.setSubTitle(_translate("Wizard_esport_modem", "Error Type(s) of the exported data file. Supported types are floor, value, egbert, egbert (floor), standard deviation, square error, and mean square error. It is also possible to configure error type(s) for each impedance component.   ", None))
        self.doubleSpinBox_error_tipper.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>Absolute tipper error, all tipper error will be set to this value unless you specify error_type as \'floor\' or \'floor_egbert\'. Default is 5%.</p></body></html>", None))
        self.doubleSpinBox_error_tipper.setSuffix(_translate("Wizard_esport_modem", "%", None))
        self.comboBox_error_type.setItemText(0, _translate("Wizard_esport_modem", "floor", None))
        self.comboBox_error_type.setItemText(1, _translate("Wizard_esport_modem", "value", None))
        self.comboBox_error_type.setItemText(2, _translate("Wizard_esport_modem", "egbert", None))
        self.comboBox_error_type.setItemText(3, _translate("Wizard_esport_modem", "egbert (floor)", None))
        self.comboBox_error_type.setItemText(4, _translate("Wizard_esport_modem", "stddev", None))
        self.comboBox_error_type.setItemText(5, _translate("Wizard_esport_modem", "square error", None))
        self.comboBox_error_type.setItemText(6, _translate("Wizard_esport_modem", "mean square error", None))
        self.doubleSpinBox_error_egbert.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>Percentage to multiply sqrt(zxy*zyx) by. Default is 3 precent as prescribed by Egbert &amp; Kelbert.</p></body></html>", None))
        self.doubleSpinBox_error_egbert.setSuffix(_translate("Wizard_esport_modem", "%", None))
        self.label_error_floor.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>Percentage to set the error floor at, anything below this number will be set to this value. Default is 10%</p></body></html>", None))
        self.label_error_floor.setText(_translate("Wizard_esport_modem", "Error Floor", None))
        self.doubleSpinBox_error_floor.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>Percentage to set the error floor at, anything below this number will be set to this value. Default is 10%</p></body></html>", None))
        self.doubleSpinBox_error_floor.setSuffix(_translate("Wizard_esport_modem", "%", None))
        self.label_error_tipper.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>Absolute tipper error, all tipper error will be set to this value unless you specify error_type as \'floor\' or \'floor_egbert\'. Default is 5%.</p></body></html>", None))
        self.label_error_tipper.setText(_translate("Wizard_esport_modem", "Error Tipper", None))
        self.label_error_egbert.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>Percentage to multiply sqrt(zxy*zyx) by. Default is 3 precent as prescribed by Egbert &amp; Kelbert.</p></body></html>", None))
        self.label_error_egbert.setText(_translate("Wizard_esport_modem", "Error Egbert", None))
        self.label.setText(_translate("Wizard_esport_modem", "Error Type", None))
        self.label_error_value.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>Percentage to multiply Z by, to set error. Default is 5 for 5% of Z as error.</p></body></html>", None))
        self.label_error_value.setText(_translate("Wizard_esport_modem", "Error Value", None))
        self.doubleSpinBox_error_value.setToolTip(_translate("Wizard_esport_modem", "<html><head/><body><p>Percentage to multiply Z by, to set error. Default is 5 for 5% of Z as error.</p></body></html>", None))
        self.doubleSpinBox_error_value.setSuffix(_translate("Wizard_esport_modem", "%", None))
        self.groupBox_3.setTitle(_translate("Wizard_esport_modem", "Component Error Type", None))
        self.checkBox_zxx.setText(_translate("Wizard_esport_modem", "zxx", None))
        self.checkBox_zxy.setText(_translate("Wizard_esport_modem", "zxy", None))
        self.comboBox_error_type_zxx.setItemText(0, _translate("Wizard_esport_modem", "floor", None))
        self.comboBox_error_type_zxx.setItemText(1, _translate("Wizard_esport_modem", "value", None))
        self.comboBox_error_type_zxx.setItemText(2, _translate("Wizard_esport_modem", "egbert", None))
        self.comboBox_error_type_zxx.setItemText(3, _translate("Wizard_esport_modem", "egbert (floor)", None))
        self.comboBox_error_type_zxx.setItemText(4, _translate("Wizard_esport_modem", "stddev", None))
        self.comboBox_error_type_zxx.setItemText(5, _translate("Wizard_esport_modem", "square error", None))
        self.comboBox_error_type_zxx.setItemText(6, _translate("Wizard_esport_modem", "mean square error", None))
        self.comboBox_error_type_zxy.setItemText(0, _translate("Wizard_esport_modem", "floor", None))
        self.comboBox_error_type_zxy.setItemText(1, _translate("Wizard_esport_modem", "value", None))
        self.comboBox_error_type_zxy.setItemText(2, _translate("Wizard_esport_modem", "egbert", None))
        self.comboBox_error_type_zxy.setItemText(3, _translate("Wizard_esport_modem", "egbert (floor)", None))
        self.comboBox_error_type_zxy.setItemText(4, _translate("Wizard_esport_modem", "stddev", None))
        self.comboBox_error_type_zxy.setItemText(5, _translate("Wizard_esport_modem", "square error", None))
        self.comboBox_error_type_zxy.setItemText(6, _translate("Wizard_esport_modem", "mean square error", None))
        self.comboBox_error_type_zyx.setItemText(0, _translate("Wizard_esport_modem", "floor", None))
        self.comboBox_error_type_zyx.setItemText(1, _translate("Wizard_esport_modem", "value", None))
        self.comboBox_error_type_zyx.setItemText(2, _translate("Wizard_esport_modem", "egbert", None))
        self.comboBox_error_type_zyx.setItemText(3, _translate("Wizard_esport_modem", "egbert (floor)", None))
        self.comboBox_error_type_zyx.setItemText(4, _translate("Wizard_esport_modem", "stddev", None))
        self.comboBox_error_type_zyx.setItemText(5, _translate("Wizard_esport_modem", "square error", None))
        self.comboBox_error_type_zyx.setItemText(6, _translate("Wizard_esport_modem", "mean square error", None))
        self.comboBox_error_type_zyy.setItemText(0, _translate("Wizard_esport_modem", "floor", None))
        self.comboBox_error_type_zyy.setItemText(1, _translate("Wizard_esport_modem", "value", None))
        self.comboBox_error_type_zyy.setItemText(2, _translate("Wizard_esport_modem", "egbert", None))
        self.comboBox_error_type_zyy.setItemText(3, _translate("Wizard_esport_modem", "egbert (floor)", None))
        self.comboBox_error_type_zyy.setItemText(4, _translate("Wizard_esport_modem", "stddev", None))
        self.comboBox_error_type_zyy.setItemText(5, _translate("Wizard_esport_modem", "square error", None))
        self.comboBox_error_type_zyy.setItemText(6, _translate("Wizard_esport_modem", "mean square error", None))
        self.checkBox_zyx.setText(_translate("Wizard_esport_modem", "zyx", None))
        self.checkBox_zyy.setText(_translate("Wizard_esport_modem", "zyy", None))
        self.wizardPage_wave_sign_unit.setTitle(_translate("Wizard_esport_modem", "Wave Sign and Unit", None))
        self.wizardPage_wave_sign_unit.setSubTitle(_translate("Wizard_esport_modem",
                                                              "Wave Sign is the sign of time dependent wave. the default is \'+\' as positive downwards.",
                                                              None))
        self.groupBox_4.setToolTip(_translate("Wizard_esport_modem",
                                              "<html><head/><body><p>Sign of time depend wave. Default is \'+\' as positive downwards.</p></body></html>",
                                              None))
        self.groupBox_4.setTitle(_translate("Wizard_esport_modem", "Wave Sign", None))
        self.groupBox_sign_impedance.setTitle(_translate("Wizard_esport_modem", "Impedances", None))
        self.radioButton_impedance_sign_plus.setText(_translate("Wizard_esport_modem", "+", None))
        self.radioButton_impedance_sign_minus.setText(_translate("Wizard_esport_modem", "-", None))
        self.groupBox_sign_vertical.setTitle(_translate("Wizard_esport_modem", "Vertical/Tipper", None))
        self.radioButton_vertical_sign_plus.setText(_translate("Wizard_esport_modem", "+", None))
        self.radioButton_vertical_sign_minus.setText(_translate("Wizard_esport_modem", "-", None))
        self.groupBox_z_unit.setToolTip(
            _translate("Wizard_esport_modem", "<html><head/><body><p>Units of Z</p></body></html>", None))
        self.groupBox_z_unit.setTitle(_translate("Wizard_esport_modem", "Z-Unit", None))
        self.radioButton_unit_vmt.setText(_translate("Wizard_esport_modem", "[V/m]/[T]", None))
        self.radioButton_unit_mvkmnt.setText(_translate("Wizard_esport_modem", "[mV/km]/[nT]", None))
        self.radioButton_unit_ohm.setText(_translate("Wizard_esport_modem", "Ohm", None))
        self.wizardPage_data.setTitle(_translate("Wizard_esport_modem", "Other Settings", None))
        self.groupBox_5.setTitle(_translate("Wizard_esport_modem", "GroupBox", None))
        self.radioButton_format_2.setText(_translate("Wizard_esport_modem", "Type 2", None))
        self.radioButton_format_1.setText(_translate("Wizard_esport_modem", "Type 1", None))
