version: 1
disable_existing_loggers: False
formatters:
    standard:
        format: "%(asctime)s [line %(lineno)d] %(name)s.%(funcName)s - %(levelname)s: %(message)s"
        datefmt: "%Y-%m-%dT%H:%M:%S"

handlers:
    console: # screen display print out
        class: logging.StreamHandler
        level: INFO
        formatter: standard
        stream: ext://sys.stdout
   

loggers:
    __main__:
        level: DEBUG
        handlers: [console]
        propagate: false

root:
    level: DEBUG
    handlers: [console]
    propogate: false
