# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\u64132\Documents\mtpy2\mtpy\gui\SmartMT\main_window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SmartMT_MainWindow(object):
    def setupUi(self, SmartMT_MainWindow):
        SmartMT_MainWindow.setObjectName(_fromUtf8("SmartMT_MainWindow"))
        SmartMT_MainWindow.resize(800, 600)
        SmartMT_MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtGui.QWidget(SmartMT_MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.mdiArea = QtGui.QMdiArea(self.centralwidget)
        self.mdiArea.setEnabled(True)
        self.mdiArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mdiArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mdiArea.setObjectName(_fromUtf8("mdiArea"))
        self.subwindow_station_viewer = QtGui.QWidget()
        self.subwindow_station_viewer.setObjectName(_fromUtf8("subwindow_station_viewer"))
        self.treeWidget_stations = QtGui.QTreeWidget(self.subwindow_station_viewer)
        self.treeWidget_stations.setGeometry(QtCore.QRect(0, 0, 371, 331))
        self.treeWidget_stations.setObjectName(_fromUtf8("treeWidget_stations"))
        self.horizontalLayout.addWidget(self.mdiArea)
        SmartMT_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(SmartMT_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuWindow = QtGui.QMenu(self.menubar)
        self.menuWindow.setObjectName(_fromUtf8("menuWindow"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        SmartMT_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(SmartMT_MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        SmartMT_MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Project = QtGui.QAction(SmartMT_MainWindow)
        self.actionNew_Project.setObjectName(_fromUtf8("actionNew_Project"))
        self.actionOpen_Project = QtGui.QAction(SmartMT_MainWindow)
        self.actionOpen_Project.setObjectName(_fromUtf8("actionOpen_Project"))
        self.actionClose_Project = QtGui.QAction(SmartMT_MainWindow)
        self.actionClose_Project.setEnabled(False)
        self.actionClose_Project.setObjectName(_fromUtf8("actionClose_Project"))
        self.actionOpen_edi_File = QtGui.QAction(SmartMT_MainWindow)
        self.actionOpen_edi_File.setObjectName(_fromUtf8("actionOpen_edi_File"))
        self.actionOpen_edi_Folder = QtGui.QAction(SmartMT_MainWindow)
        self.actionOpen_edi_Folder.setObjectName(_fromUtf8("actionOpen_edi_Folder"))
        self.actionSave_as_Project = QtGui.QAction(SmartMT_MainWindow)
        self.actionSave_as_Project.setEnabled(False)
        self.actionSave_as_Project.setObjectName(_fromUtf8("actionSave_as_Project"))
        self.actionSave_Project = QtGui.QAction(SmartMT_MainWindow)
        self.actionSave_Project.setEnabled(False)
        self.actionSave_Project.setObjectName(_fromUtf8("actionSave_Project"))
        self.actionExit = QtGui.QAction(SmartMT_MainWindow)
        self.actionExit.setStatusTip(_fromUtf8(""))
        self.actionExit.setMenuRole(QtGui.QAction.QuitRole)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionExport = QtGui.QAction(SmartMT_MainWindow)
        self.actionExport.setObjectName(_fromUtf8("actionExport"))
        self.actionShow_Data_Collection = QtGui.QAction(SmartMT_MainWindow)
        self.actionShow_Data_Collection.setCheckable(True)
        self.actionShow_Data_Collection.setChecked(True)
        self.actionShow_Data_Collection.setEnabled(False)
        self.actionShow_Data_Collection.setObjectName(_fromUtf8("actionShow_Data_Collection"))
        self.actionFind_Action = QtGui.QAction(SmartMT_MainWindow)
        self.actionFind_Action.setObjectName(_fromUtf8("actionFind_Action"))
        self.actionHelp = QtGui.QAction(SmartMT_MainWindow)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionAbout = QtGui.QAction(SmartMT_MainWindow)
        self.actionAbout.setMenuRole(QtGui.QAction.AboutRole)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionOptions = QtGui.QAction(SmartMT_MainWindow)
        self.actionOptions.setMenuRole(QtGui.QAction.PreferencesRole)
        self.actionOptions.setObjectName(_fromUtf8("actionOptions"))
        self.menuFile.addAction(self.actionNew_Project)
        self.menuFile.addAction(self.actionOpen_Project)
        self.menuFile.addAction(self.actionSave_Project)
        self.menuFile.addAction(self.actionClose_Project)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_edi_File)
        self.menuFile.addAction(self.actionOpen_edi_Folder)
        self.menuFile.addAction(self.actionSave_as_Project)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuView.addAction(self.actionShow_Data_Collection)
        self.menuHelp.addAction(self.actionFind_Action)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuTools.addAction(self.actionOptions)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(SmartMT_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(SmartMT_MainWindow)

    def retranslateUi(self, SmartMT_MainWindow):
        SmartMT_MainWindow.setWindowTitle(_translate("SmartMT_MainWindow", "SmartMT", None))
        self.subwindow_station_viewer.setWindowTitle(_translate("SmartMT_MainWindow", "Subwindow", None))
        self.treeWidget_stations.headerItem().setText(0, _translate("SmartMT_MainWindow", "Group", None))
        self.treeWidget_stations.headerItem().setText(1, _translate("SmartMT_MainWindow", "New Column", None))
        self.treeWidget_stations.headerItem().setText(2, _translate("SmartMT_MainWindow", "File", None))
        self.menuFile.setTitle(_translate("SmartMT_MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("SmartMT_MainWindow", "Edit", None))
        self.menuView.setTitle(_translate("SmartMT_MainWindow", "View", None))
        self.menuWindow.setTitle(_translate("SmartMT_MainWindow", "Window", None))
        self.menuHelp.setTitle(_translate("SmartMT_MainWindow", "Help", None))
        self.menuTools.setTitle(_translate("SmartMT_MainWindow", "Tools", None))
        self.actionNew_Project.setText(_translate("SmartMT_MainWindow", "New Project...", None))
        self.actionNew_Project.setShortcut(_translate("SmartMT_MainWindow", "Alt+N", None))
        self.actionOpen_Project.setText(_translate("SmartMT_MainWindow", "Open Project...", None))
        self.actionClose_Project.setText(_translate("SmartMT_MainWindow", "Close Project", None))
        self.actionOpen_edi_File.setText(_translate("SmartMT_MainWindow", "Open .edi File...", None))
        self.actionOpen_edi_Folder.setText(_translate("SmartMT_MainWindow", "Open .edi Folder...", None))
        self.actionSave_as_Project.setText(_translate("SmartMT_MainWindow", "Save as Project...", None))
        self.actionSave_Project.setText(_translate("SmartMT_MainWindow", "Save Project...", None))
        self.actionExit.setText(_translate("SmartMT_MainWindow", "Exit", None))
        self.actionExport.setText(_translate("SmartMT_MainWindow", "Export...", None))
        self.actionShow_Data_Collection.setText(_translate("SmartMT_MainWindow", "Show Data Collection", None))
        self.actionFind_Action.setText(_translate("SmartMT_MainWindow", "Find Action...", None))
        self.actionHelp.setText(_translate("SmartMT_MainWindow", "Help", None))
        self.actionAbout.setText(_translate("SmartMT_MainWindow", "About", None))
        self.actionOptions.setText(_translate("SmartMT_MainWindow", "Options...", None))

