# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fourthgui.ui'
#
# Created: Wed Sep  5 11:35:55 2012
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_occamgui2D(object):
    def setupUi(self, occamgui2D):
        occamgui2D.setObjectName("occamgui2D")
        occamgui2D.resize(900, 674)
        occamgui2D.setMinimumSize(QtCore.QSize(400, 0))
        self.label_29 = QtGui.QLabel(occamgui2D)
        self.label_29.setGeometry(QtCore.QRect(11, 16, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_4 = QtGui.QLabel(occamgui2D)
        self.label_4.setGeometry(QtCore.QRect(10, 49, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.layoutWidget_15 = QtGui.QWidget(occamgui2D)
        self.layoutWidget_15.setGeometry(QtCore.QRect(38, 504, 845, 72))
        self.layoutWidget_15.setObjectName("layoutWidget_15")
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget_15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_11 = QtGui.QLabel(self.layoutWidget_15)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_20.addWidget(self.label_11)
        self.doubleSpinBox_errorvalue_resXY = QtGui.QDoubleSpinBox(self.layoutWidget_15)
        self.doubleSpinBox_errorvalue_resXY.setMinimumSize(QtCore.QSize(0, 30))
        self.doubleSpinBox_errorvalue_resXY.setMaximumSize(QtCore.QSize(16777215, 30))
        self.doubleSpinBox_errorvalue_resXY.setDecimals(0)
        self.doubleSpinBox_errorvalue_resXY.setMinimum(0.0)
        self.doubleSpinBox_errorvalue_resXY.setMaximum(100.0)
        self.doubleSpinBox_errorvalue_resXY.setSingleStep(1.0)
        self.doubleSpinBox_errorvalue_resXY.setObjectName("doubleSpinBox_errorvalue_resXY")
        self.horizontalLayout_20.addWidget(self.doubleSpinBox_errorvalue_resXY)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem)
        self.checkBox_usedataerror_resXY = QtGui.QCheckBox(self.layoutWidget_15)
        self.checkBox_usedataerror_resXY.setObjectName("checkBox_usedataerror_resXY")
        self.horizontalLayout_20.addWidget(self.checkBox_usedataerror_resXY)
        self.gridLayout_2.addLayout(self.horizontalLayout_20, 0, 0, 1, 1)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem1)
        self.label_13 = QtGui.QLabel(self.layoutWidget_15)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_24.addWidget(self.label_13)
        self.doubleSpinBox_errorvalue_phaseXY = QtGui.QDoubleSpinBox(self.layoutWidget_15)
        self.doubleSpinBox_errorvalue_phaseXY.setMinimumSize(QtCore.QSize(0, 30))
        self.doubleSpinBox_errorvalue_phaseXY.setMaximumSize(QtCore.QSize(16777215, 30))
        self.doubleSpinBox_errorvalue_phaseXY.setDecimals(0)
        self.doubleSpinBox_errorvalue_phaseXY.setMinimum(0.0)
        self.doubleSpinBox_errorvalue_phaseXY.setMaximum(100.0)
        self.doubleSpinBox_errorvalue_phaseXY.setSingleStep(1.0)
        self.doubleSpinBox_errorvalue_phaseXY.setObjectName("doubleSpinBox_errorvalue_phaseXY")
        self.horizontalLayout_24.addWidget(self.doubleSpinBox_errorvalue_phaseXY)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem2)
        self.checkBox_usedataerror_phaseXY = QtGui.QCheckBox(self.layoutWidget_15)
        self.checkBox_usedataerror_phaseXY.setObjectName("checkBox_usedataerror_phaseXY")
        self.horizontalLayout_24.addWidget(self.checkBox_usedataerror_phaseXY)
        self.gridLayout_2.addLayout(self.horizontalLayout_24, 0, 3, 1, 1)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_12 = QtGui.QLabel(self.layoutWidget_15)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_26.addWidget(self.label_12)
        self.doubleSpinBox_errorvalue_resYX = QtGui.QDoubleSpinBox(self.layoutWidget_15)
        self.doubleSpinBox_errorvalue_resYX.setMinimumSize(QtCore.QSize(0, 30))
        self.doubleSpinBox_errorvalue_resYX.setMaximumSize(QtCore.QSize(16777215, 30))
        self.doubleSpinBox_errorvalue_resYX.setDecimals(0)
        self.doubleSpinBox_errorvalue_resYX.setMinimum(0.0)
        self.doubleSpinBox_errorvalue_resYX.setMaximum(100.0)
        self.doubleSpinBox_errorvalue_resYX.setSingleStep(1.0)
        self.doubleSpinBox_errorvalue_resYX.setObjectName("doubleSpinBox_errorvalue_resYX")
        self.horizontalLayout_26.addWidget(self.doubleSpinBox_errorvalue_resYX)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem3)
        self.checkBox_usedataerror_resYX = QtGui.QCheckBox(self.layoutWidget_15)
        self.checkBox_usedataerror_resYX.setObjectName("checkBox_usedataerror_resYX")
        self.horizontalLayout_26.addWidget(self.checkBox_usedataerror_resYX)
        self.gridLayout_2.addLayout(self.horizontalLayout_26, 1, 0, 1, 1)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem4)
        self.label_14 = QtGui.QLabel(self.layoutWidget_15)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_27.addWidget(self.label_14)
        self.doubleSpinBox_errorvalue_phaseYX = QtGui.QDoubleSpinBox(self.layoutWidget_15)
        self.doubleSpinBox_errorvalue_phaseYX.setMinimumSize(QtCore.QSize(0, 30))
        self.doubleSpinBox_errorvalue_phaseYX.setMaximumSize(QtCore.QSize(16777215, 30))
        self.doubleSpinBox_errorvalue_phaseYX.setDecimals(0)
        self.doubleSpinBox_errorvalue_phaseYX.setMinimum(0.0)
        self.doubleSpinBox_errorvalue_phaseYX.setMaximum(100.0)
        self.doubleSpinBox_errorvalue_phaseYX.setSingleStep(1.0)
        self.doubleSpinBox_errorvalue_phaseYX.setObjectName("doubleSpinBox_errorvalue_phaseYX")
        self.horizontalLayout_27.addWidget(self.doubleSpinBox_errorvalue_phaseYX)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem5)
        self.checkBox_usedataerror_phaseYX = QtGui.QCheckBox(self.layoutWidget_15)
        self.checkBox_usedataerror_phaseYX.setObjectName("checkBox_usedataerror_phaseYX")
        self.horizontalLayout_27.addWidget(self.checkBox_usedataerror_phaseYX)
        self.gridLayout_2.addLayout(self.horizontalLayout_27, 1, 3, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 0, 1, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 1, 1, 1, 1)
        self.line_4 = QtGui.QFrame(self.layoutWidget_15)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_2.addWidget(self.line_4, 0, 2, 1, 1)
        self.line_7 = QtGui.QFrame(self.layoutWidget_15)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_2.addWidget(self.line_7, 1, 2, 1, 1)
        self.pushButton_generateinputfile = QtGui.QPushButton(occamgui2D)
        self.pushButton_generateinputfile.setGeometry(QtCore.QRect(230, 620, 138, 30))
        self.pushButton_generateinputfile.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_generateinputfile.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_generateinputfile.setAutoDefault(True)
        self.pushButton_generateinputfile.setObjectName("pushButton_generateinputfile")
        self.pushButton_loadold_meshinmodel = QtGui.QPushButton(occamgui2D)
        self.pushButton_loadold_meshinmodel.setGeometry(QtCore.QRect(560, 620, 158, 30))
        self.pushButton_loadold_meshinmodel.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_loadold_meshinmodel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_loadold_meshinmodel.setAutoDefault(True)
        self.pushButton_loadold_meshinmodel.setObjectName("pushButton_loadold_meshinmodel")
        self.line = QtGui.QFrame(occamgui2D)
        self.line.setGeometry(QtCore.QRect(480, 618, 20, 34))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget = QtGui.QWidget(occamgui2D)
        self.layoutWidget.setGeometry(QtCore.QRect(238, 21, 638, 262))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.gridLayout.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.button_browse_wd = QtGui.QToolButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_browse_wd.sizePolicy().hasHeightForWidth())
        self.button_browse_wd.setSizePolicy(sizePolicy)
        self.button_browse_wd.setMinimumSize(QtCore.QSize(30, 25))
        self.button_browse_wd.setMaximumSize(QtCore.QSize(30, 25))
        self.button_browse_wd.setObjectName("button_browse_wd")
        self.horizontalLayout_2.addWidget(self.button_browse_wd)
        self.lineEdit_browse_wd = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_browse_wd.setMinimumSize(QtCore.QSize(300, 30))
        self.lineEdit_browse_wd.setMaximumSize(QtCore.QSize(500, 30))
        self.lineEdit_browse_wd.setObjectName("lineEdit_browse_wd")
        self.horizontalLayout_2.addWidget(self.lineEdit_browse_wd)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 1, 1, 2)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.gridLayout.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.button_browse_occam = QtGui.QToolButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_browse_occam.sizePolicy().hasHeightForWidth())
        self.button_browse_occam.setSizePolicy(sizePolicy)
        self.button_browse_occam.setMinimumSize(QtCore.QSize(30, 25))
        self.button_browse_occam.setMaximumSize(QtCore.QSize(30, 25))
        self.button_browse_occam.setObjectName("button_browse_occam")
        self.horizontalLayout_3.addWidget(self.button_browse_occam)
        self.lineEdit_browse_occam = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_browse_occam.setMinimumSize(QtCore.QSize(300, 30))
        self.lineEdit_browse_occam.setMaximumSize(QtCore.QSize(500, 30))
        self.lineEdit_browse_occam.setObjectName("lineEdit_browse_occam")
        self.horizontalLayout_3.addWidget(self.lineEdit_browse_occam)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 1, 1, 2)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem12)
        self.gridLayout.addLayout(self.horizontalLayout_10, 2, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem13)
        self.button_browse_makemodel = QtGui.QToolButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_browse_makemodel.sizePolicy().hasHeightForWidth())
        self.button_browse_makemodel.setSizePolicy(sizePolicy)
        self.button_browse_makemodel.setMinimumSize(QtCore.QSize(30, 25))
        self.button_browse_makemodel.setMaximumSize(QtCore.QSize(30, 25))
        self.button_browse_makemodel.setObjectName("button_browse_makemodel")
        self.horizontalLayout.addWidget(self.button_browse_makemodel)
        self.lineEdit_browse_makemodel = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_browse_makemodel.setMinimumSize(QtCore.QSize(300, 30))
        self.lineEdit_browse_makemodel.setMaximumSize(QtCore.QSize(500, 30))
        self.lineEdit_browse_makemodel.setObjectName("lineEdit_browse_makemodel")
        self.horizontalLayout.addWidget(self.lineEdit_browse_makemodel)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 2)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_28 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_11.addWidget(self.label_28)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem14)
        self.gridLayout.addLayout(self.horizontalLayout_11, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem15)
        self.button_browse_edis = QtGui.QToolButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_browse_edis.sizePolicy().hasHeightForWidth())
        self.button_browse_edis.setSizePolicy(sizePolicy)
        self.button_browse_edis.setMinimumSize(QtCore.QSize(30, 25))
        self.button_browse_edis.setMaximumSize(QtCore.QSize(30, 25))
        self.button_browse_edis.setObjectName("button_browse_edis")
        self.horizontalLayout_4.addWidget(self.button_browse_edis)
        self.lineEdit_browse_edis = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_browse_edis.setMinimumSize(QtCore.QSize(300, 30))
        self.lineEdit_browse_edis.setMaximumSize(QtCore.QSize(500, 30))
        self.lineEdit_browse_edis.setObjectName("lineEdit_browse_edis")
        self.horizontalLayout_4.addWidget(self.lineEdit_browse_edis)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 1, 1, 2)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.checkBox_usestationlist = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_usestationlist.setObjectName("checkBox_usestationlist")
        self.horizontalLayout_12.addWidget(self.checkBox_usestationlist)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem16)
        self.gridLayout.addLayout(self.horizontalLayout_12, 4, 0, 1, 2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem17)
        self.button_browse_stations = QtGui.QToolButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_browse_stations.sizePolicy().hasHeightForWidth())
        self.button_browse_stations.setSizePolicy(sizePolicy)
        self.button_browse_stations.setMinimumSize(QtCore.QSize(30, 25))
        self.button_browse_stations.setMaximumSize(QtCore.QSize(30, 25))
        self.button_browse_stations.setObjectName("button_browse_stations")
        self.horizontalLayout_5.addWidget(self.button_browse_stations)
        self.lineEdit_browse_stations = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_browse_stations.setMinimumSize(QtCore.QSize(300, 30))
        self.lineEdit_browse_stations.setMaximumSize(QtCore.QSize(500, 30))
        self.lineEdit_browse_stations.setObjectName("lineEdit_browse_stations")
        self.horizontalLayout_5.addWidget(self.lineEdit_browse_stations)
        self.gridLayout.addLayout(self.horizontalLayout_5, 4, 2, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.checkBox_usedatafile = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_usedatafile.setObjectName("checkBox_usedatafile")
        self.horizontalLayout_13.addWidget(self.checkBox_usedatafile)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem18)
        self.gridLayout.addLayout(self.horizontalLayout_13, 5, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem19)
        self.pushButton_loaddatafile = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_loaddatafile.sizePolicy().hasHeightForWidth())
        self.pushButton_loaddatafile.setSizePolicy(sizePolicy)
        self.pushButton_loaddatafile.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_loaddatafile.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_loaddatafile.setAutoDefault(True)
        self.pushButton_loaddatafile.setObjectName("pushButton_loaddatafile")
        self.horizontalLayout_6.addWidget(self.pushButton_loaddatafile)
        self.lineEdit_browse_datafile = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_browse_datafile.setMinimumSize(QtCore.QSize(300, 30))
        self.lineEdit_browse_datafile.setMaximumSize(QtCore.QSize(500, 30))
        self.lineEdit_browse_datafile.setObjectName("lineEdit_browse_datafile")
        self.horizontalLayout_6.addWidget(self.lineEdit_browse_datafile)
        self.gridLayout.addLayout(self.horizontalLayout_6, 5, 1, 1, 2)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_14.addWidget(self.label_3)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem20)
        self.gridLayout.addLayout(self.horizontalLayout_14, 6, 0, 1, 2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem21)
        self.lineEdit_browse_datafilename = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_browse_datafilename.sizePolicy().hasHeightForWidth())
        self.lineEdit_browse_datafilename.setSizePolicy(sizePolicy)
        self.lineEdit_browse_datafilename.setMinimumSize(QtCore.QSize(300, 30))
        self.lineEdit_browse_datafilename.setMaximumSize(QtCore.QSize(500, 30))
        self.lineEdit_browse_datafilename.setObjectName("lineEdit_browse_datafilename")
        self.horizontalLayout_7.addWidget(self.lineEdit_browse_datafilename)
        self.gridLayout.addLayout(self.horizontalLayout_7, 6, 2, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(occamgui2D)
        self.layoutWidget1.setGeometry(QtCore.QRect(130, 297, 743, 116))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_modelname = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEdit_modelname.setObjectName("lineEdit_modelname")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_modelname)
        self.horizontalLayout_29.addLayout(self.formLayout_2)
        spacerItem22 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem22)
        self.gridLayout_3.addLayout(self.horizontalLayout_29, 0, 0, 1, 1)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        spacerItem23 = QtGui.QSpacerItem(17, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem23)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_8 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.comboBox_mode = QtGui.QComboBox(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_mode.sizePolicy().hasHeightForWidth())
        self.comboBox_mode.setSizePolicy(sizePolicy)
        self.comboBox_mode.setMinimumSize(QtCore.QSize(90, 25))
        self.comboBox_mode.setMaximumSize(QtCore.QSize(16777215, 30))
        self.comboBox_mode.setObjectName("comboBox_mode")
        self.comboBox_mode.addItem("")
        self.comboBox_mode.addItem("")
        self.comboBox_mode.addItem("")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBox_mode)
        self.horizontalLayout_28.addLayout(self.formLayout)
        self.gridLayout_3.addLayout(self.horizontalLayout_28, 0, 1, 1, 1)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        spacerItem24 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem24)
        self.label_15 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMaximumSize(QtCore.QSize(110, 30))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_25.addWidget(self.label_15)
        self.spinBox_freq_steps = QtGui.QSpinBox(self.layoutWidget1)
        self.spinBox_freq_steps.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_freq_steps.sizePolicy().hasHeightForWidth())
        self.spinBox_freq_steps.setSizePolicy(sizePolicy)
        self.spinBox_freq_steps.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBox_freq_steps.setMaximumSize(QtCore.QSize(50, 30))
        self.spinBox_freq_steps.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_freq_steps.setMinimum(1)
        self.spinBox_freq_steps.setObjectName("spinBox_freq_steps")
        self.horizontalLayout_25.addWidget(self.spinBox_freq_steps)
        self.gridLayout_3.addLayout(self.horizontalLayout_25, 0, 2, 1, 2)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.formLayout_6 = QtGui.QFormLayout()
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_23 = QtGui.QLabel(self.layoutWidget1)
        self.label_23.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_23.setFrameShadow(QtGui.QFrame.Plain)
        self.label_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_23)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.doubleSpinBox_strike = QtGui.QDoubleSpinBox(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_strike.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_strike.setSizePolicy(sizePolicy)
        self.doubleSpinBox_strike.setMinimumSize(QtCore.QSize(0, 30))
        self.doubleSpinBox_strike.setMaximumSize(QtCore.QSize(16777215, 30))
        self.doubleSpinBox_strike.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_strike.setMinimum(-90.0)
        self.doubleSpinBox_strike.setMaximum(90.0)
        self.doubleSpinBox_strike.setSingleStep(0.1)
        self.doubleSpinBox_strike.setObjectName("doubleSpinBox_strike")
        self.horizontalLayout_17.addWidget(self.doubleSpinBox_strike)
        self.label_25 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_17.addWidget(self.label_25)
        self.formLayout_6.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_17)
        self.horizontalLayout_31.addLayout(self.formLayout_6)
        spacerItem25 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem25)
        self.gridLayout_3.addLayout(self.horizontalLayout_31, 1, 0, 1, 1)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        spacerItem26 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem26)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_9 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(0, 0))
        self.label_9.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_9.setObjectName("label_9")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_9)
        self.comboBox_alignment = QtGui.QComboBox(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_alignment.sizePolicy().hasHeightForWidth())
        self.comboBox_alignment.setSizePolicy(sizePolicy)
        self.comboBox_alignment.setMinimumSize(QtCore.QSize(55, 25))
        self.comboBox_alignment.setMaximumSize(QtCore.QSize(55, 30))
        self.comboBox_alignment.setObjectName("comboBox_alignment")
        self.comboBox_alignment.addItem("")
        self.comboBox_alignment.addItem("")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBox_alignment)
        self.horizontalLayout_30.addLayout(self.formLayout_4)
        self.gridLayout_3.addLayout(self.horizontalLayout_30, 1, 1, 1, 2)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        spacerItem27 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem27)
        self.widget = QtGui.QWidget(self.layoutWidget1)
        self.widget.setObjectName("widget")
        self.horizontalLayout_23.addWidget(self.widget)
        self.gridLayout_3.addLayout(self.horizontalLayout_23, 1, 3, 1, 1)
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_21 = QtGui.QLabel(self.layoutWidget1)
        self.label_21.setObjectName("label_21")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_21)
        self.doubleSpinBox_mergethreshold = QtGui.QDoubleSpinBox(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_mergethreshold.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_mergethreshold.setSizePolicy(sizePolicy)
        self.doubleSpinBox_mergethreshold.setMinimumSize(QtCore.QSize(0, 30))
        self.doubleSpinBox_mergethreshold.setMaximumSize(QtCore.QSize(16777215, 30))
        self.doubleSpinBox_mergethreshold.setMaximum(100.0)
        self.doubleSpinBox_mergethreshold.setProperty("value", 0.75)
        self.doubleSpinBox_mergethreshold.setObjectName("doubleSpinBox_mergethreshold")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_mergethreshold)
        self.horizontalLayout_32.addLayout(self.formLayout_5)
        spacerItem28 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem28)
        self.gridLayout_3.addLayout(self.horizontalLayout_32, 2, 0, 1, 1)
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        spacerItem29 = QtGui.QSpacerItem(2, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem29)
        self.formLayout_8 = QtGui.QFormLayout()
        self.formLayout_8.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_16 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_16)
        self.spinBox_iterations = QtGui.QSpinBox(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_iterations.sizePolicy().hasHeightForWidth())
        self.spinBox_iterations.setSizePolicy(sizePolicy)
        self.spinBox_iterations.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBox_iterations.setMaximumSize(QtCore.QSize(50, 30))
        self.spinBox_iterations.setMinimum(1)
        self.spinBox_iterations.setObjectName("spinBox_iterations")
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinBox_iterations)
        self.horizontalLayout_33.addLayout(self.formLayout_8)
        self.gridLayout_3.addLayout(self.horizontalLayout_33, 2, 1, 1, 1)
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        spacerItem30 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem30)
        self.formLayout_7 = QtGui.QFormLayout()
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_17 = QtGui.QLabel(self.layoutWidget1)
        self.label_17.setObjectName("label_17")
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_17)
        self.doubleSpinBox_rms = QtGui.QDoubleSpinBox(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_rms.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_rms.setSizePolicy(sizePolicy)
        self.doubleSpinBox_rms.setMinimumSize(QtCore.QSize(0, 30))
        self.doubleSpinBox_rms.setMaximumSize(QtCore.QSize(16777215, 30))
        self.doubleSpinBox_rms.setMinimum(0.01)
        self.doubleSpinBox_rms.setMaximum(100.0)
        self.doubleSpinBox_rms.setSingleStep(0.01)
        self.doubleSpinBox_rms.setProperty("value", 1.0)
        self.doubleSpinBox_rms.setObjectName("doubleSpinBox_rms")
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_rms)
        self.horizontalLayout_34.addLayout(self.formLayout_7)
        self.gridLayout_3.addLayout(self.horizontalLayout_34, 2, 2, 1, 2)
        self.layoutWidget2 = QtGui.QWidget(occamgui2D)
        self.layoutWidget2.setGeometry(QtCore.QRect(88, 426, 785, 38))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_18 = QtGui.QLabel(self.layoutWidget2)
        self.label_18.setObjectName("label_18")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_18)
        self.spinBox_layers = QtGui.QSpinBox(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_layers.sizePolicy().hasHeightForWidth())
        self.spinBox_layers.setSizePolicy(sizePolicy)
        self.spinBox_layers.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBox_layers.setMaximumSize(QtCore.QSize(600, 30))
        self.spinBox_layers.setMinimum(1)
        self.spinBox_layers.setMaximum(1000)
        self.spinBox_layers.setProperty("value", 100)
        self.spinBox_layers.setObjectName("spinBox_layers")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinBox_layers)
        self.horizontalLayout_36.addLayout(self.formLayout_3)
        spacerItem31 = QtGui.QSpacerItem(2, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem31)
        self.gridLayout_4.addLayout(self.horizontalLayout_36, 0, 0, 1, 1)
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        spacerItem32 = QtGui.QSpacerItem(2, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(spacerItem32)
        self.formLayout_10 = QtGui.QFormLayout()
        self.formLayout_10.setObjectName("formLayout_10")
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_26 = QtGui.QLabel(self.layoutWidget2)
        self.label_26.setMinimumSize(QtCore.QSize(143, 0))
        self.label_26.setMaximumSize(QtCore.QSize(170, 16777215))
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_21.addWidget(self.label_26)
        self.spinBox_firstlayer = QtGui.QSpinBox(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_firstlayer.sizePolicy().hasHeightForWidth())
        self.spinBox_firstlayer.setSizePolicy(sizePolicy)
        self.spinBox_firstlayer.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBox_firstlayer.setMaximumSize(QtCore.QSize(500, 30))
        self.spinBox_firstlayer.setMinimum(1)
        self.spinBox_firstlayer.setMaximum(10000)
        self.spinBox_firstlayer.setProperty("value", 100)
        self.spinBox_firstlayer.setObjectName("spinBox_firstlayer")
        self.horizontalLayout_21.addWidget(self.spinBox_firstlayer)
        self.label_27 = QtGui.QLabel(self.layoutWidget2)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_21.addWidget(self.label_27)
        self.formLayout_10.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_21)
        self.horizontalLayout_37.addLayout(self.formLayout_10)
        self.gridLayout_4.addLayout(self.horizontalLayout_37, 0, 1, 1, 1)
        self.horizontalLayout_38 = QtGui.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        spacerItem33 = QtGui.QSpacerItem(2, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem33)
        self.formLayout_11 = QtGui.QFormLayout()
        self.formLayout_11.setObjectName("formLayout_11")
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_20 = QtGui.QLabel(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(140, 0))
        self.label_20.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_18.addWidget(self.label_20)
        self.spinBox_maxblockwidth = QtGui.QSpinBox(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_maxblockwidth.sizePolicy().hasHeightForWidth())
        self.spinBox_maxblockwidth.setSizePolicy(sizePolicy)
        self.spinBox_maxblockwidth.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBox_maxblockwidth.setMaximumSize(QtCore.QSize(500, 30))
        self.spinBox_maxblockwidth.setMinimum(1000)
        self.spinBox_maxblockwidth.setMaximum(100000)
        self.spinBox_maxblockwidth.setProperty("value", 1000)
        self.spinBox_maxblockwidth.setObjectName("spinBox_maxblockwidth")
        self.horizontalLayout_18.addWidget(self.spinBox_maxblockwidth)
        self.label_22 = QtGui.QLabel(self.layoutWidget2)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_18.addWidget(self.label_22)
        self.formLayout_11.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_18)
        self.horizontalLayout_38.addLayout(self.formLayout_11)
        self.gridLayout_4.addLayout(self.horizontalLayout_38, 0, 2, 1, 1)
        self.layoutWidget3 = QtGui.QWidget(occamgui2D)
        self.layoutWidget3.setGeometry(QtCore.QRect(139, 463, 743, 38))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_39 = QtGui.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.formLayout_14 = QtGui.QFormLayout()
        self.formLayout_14.setObjectName("formLayout_14")
        self.label_19 = QtGui.QLabel(self.layoutWidget3)
        self.label_19.setObjectName("label_19")
        self.formLayout_14.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_19)
        self.spinBox_layersperdecade = QtGui.QSpinBox(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_layersperdecade.sizePolicy().hasHeightForWidth())
        self.spinBox_layersperdecade.setSizePolicy(sizePolicy)
        self.spinBox_layersperdecade.setMinimumSize(QtCore.QSize(0, 30))
        self.spinBox_layersperdecade.setMaximumSize(QtCore.QSize(50, 30))
        self.spinBox_layersperdecade.setMinimum(1)
        self.spinBox_layersperdecade.setMaximum(100)
        self.spinBox_layersperdecade.setProperty("value", 30)
        self.spinBox_layersperdecade.setObjectName("spinBox_layersperdecade")
        self.formLayout_14.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinBox_layersperdecade)
        self.horizontalLayout_39.addLayout(self.formLayout_14)
        spacerItem34 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem34)
        self.gridLayout_5.addLayout(self.horizontalLayout_39, 0, 0, 1, 1)
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        spacerItem35 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem35)
        self.formLayout_13 = QtGui.QFormLayout()
        self.formLayout_13.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_13.setObjectName("formLayout_13")
        self.formLayout_12 = QtGui.QFormLayout()
        self.formLayout_12.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_12.setObjectName("formLayout_12")
        self.doubleSpinBox_rhostart = QtGui.QDoubleSpinBox(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_rhostart.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_rhostart.setSizePolicy(sizePolicy)
        self.doubleSpinBox_rhostart.setMinimumSize(QtCore.QSize(0, 30))
        self.doubleSpinBox_rhostart.setMaximumSize(QtCore.QSize(16777215, 30))
        self.doubleSpinBox_rhostart.setDecimals(1)
        self.doubleSpinBox_rhostart.setMaximum(100000.0)
        self.doubleSpinBox_rhostart.setProperty("value", 100.0)
        self.doubleSpinBox_rhostart.setObjectName("doubleSpinBox_rhostart")
        self.formLayout_12.setWidget(0, QtGui.QFormLayout.LabelRole, self.doubleSpinBox_rhostart)
        self.label_30 = QtGui.QLabel(self.layoutWidget3)
        self.label_30.setObjectName("label_30")
        self.formLayout_12.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_30)
        self.formLayout_13.setLayout(0, QtGui.QFormLayout.FieldRole, self.formLayout_12)
        self.label_24 = QtGui.QLabel(self.layoutWidget3)
        self.label_24.setObjectName("label_24")
        self.formLayout_13.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_24)
        self.horizontalLayout_35.addLayout(self.formLayout_13)
        self.gridLayout_5.addLayout(self.horizontalLayout_35, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(occamgui2D)
        self.label_10.setGeometry(QtCore.QRect(511, 581, 73, 30))
        self.label_10.setMinimumSize(QtCore.QSize(0, 30))
        self.label_10.setObjectName("label_10")
        self.checkBox_usetipper = QtGui.QCheckBox(occamgui2D)
        self.checkBox_usetipper.setGeometry(QtCore.QRect(343, 581, 116, 30))
        self.checkBox_usetipper.setMinimumSize(QtCore.QSize(0, 30))
        self.checkBox_usetipper.setMaximumSize(QtCore.QSize(16777215, 30))
        self.checkBox_usetipper.setObjectName("checkBox_usetipper")
        self.doubleSpinBox_errorvalue_tipper = QtGui.QDoubleSpinBox(occamgui2D)
        self.doubleSpinBox_errorvalue_tipper.setGeometry(QtCore.QRect(590, 581, 49, 30))
        self.doubleSpinBox_errorvalue_tipper.setMinimumSize(QtCore.QSize(0, 30))
        self.doubleSpinBox_errorvalue_tipper.setMaximumSize(QtCore.QSize(16777215, 30))
        self.doubleSpinBox_errorvalue_tipper.setDecimals(0)
        self.doubleSpinBox_errorvalue_tipper.setMinimum(0.0)
        self.doubleSpinBox_errorvalue_tipper.setMaximum(100.0)
        self.doubleSpinBox_errorvalue_tipper.setSingleStep(1.0)
        self.doubleSpinBox_errorvalue_tipper.setObjectName("doubleSpinBox_errorvalue_tipper")
        self.pushButton_checkparameter = QtGui.QPushButton(occamgui2D)
        self.pushButton_checkparameter.setGeometry(QtCore.QRect(39, 620, 129, 30))
        self.pushButton_checkparameter.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_checkparameter.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_checkparameter.setAutoDefault(True)
        self.pushButton_checkparameter.setObjectName("pushButton_checkparameter")
        self.pushButton_runoccam = QtGui.QPushButton(occamgui2D)
        self.pushButton_runoccam.setGeometry(QtCore.QRect(771, 620, 110, 30))
        self.pushButton_runoccam.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_runoccam.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_runoccam.setAutoDefault(True)
        self.pushButton_runoccam.setObjectName("pushButton_runoccam")
        self.label_11.setBuddy(self.doubleSpinBox_errorvalue_resXY)
        self.label_13.setBuddy(self.doubleSpinBox_errorvalue_phaseXY)
        self.label_12.setBuddy(self.doubleSpinBox_errorvalue_resYX)
        self.label_14.setBuddy(self.doubleSpinBox_errorvalue_phaseYX)
        self.label_15.setBuddy(self.spinBox_freq_steps)
        self.label_23.setBuddy(self.doubleSpinBox_strike)
        self.label_21.setBuddy(self.doubleSpinBox_mergethreshold)
        self.label_16.setBuddy(self.spinBox_iterations)
        self.label_17.setBuddy(self.doubleSpinBox_rms)
        self.label_18.setBuddy(self.spinBox_layers)
        self.label_26.setBuddy(self.spinBox_firstlayer)
        self.label_20.setBuddy(self.spinBox_maxblockwidth)
        self.label_19.setBuddy(self.spinBox_layersperdecade)
        self.label_24.setBuddy(self.doubleSpinBox_rhostart)

        self.retranslateUi(occamgui2D)
        QtCore.QMetaObject.connectSlotsByName(occamgui2D)

    def retranslateUi(self, occamgui2D):
        occamgui2D.setWindowTitle(QtGui.QApplication.translate("occamgui2D", "OCCAM 2D GUI - II", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("occamgui2D", "Modelling-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("occamgui2D", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("occamgui2D", "Resistitvity XY Error", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_usedataerror_resXY.setText(QtGui.QApplication.translate("occamgui2D", "use data intrinsic error value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("occamgui2D", "Phase XY Error", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_usedataerror_phaseXY.setText(QtGui.QApplication.translate("occamgui2D", "use data intrinsic error value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("occamgui2D", "Resistitvity YX Error", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_usedataerror_resYX.setText(QtGui.QApplication.translate("occamgui2D", "use data intrinsic error value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("occamgui2D", "Phase YX Error", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_usedataerror_phaseYX.setText(QtGui.QApplication.translate("occamgui2D", "use data intrinsic error value", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_generateinputfile.setText(QtGui.QApplication.translate("occamgui2D", "Generate input files", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_loadold_meshinmodel.setText(QtGui.QApplication.translate("occamgui2D", "Load old Mesh/Inmodel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("occamgui2D", "working directory", None, QtGui.QApplication.UnicodeUTF8))
        self.button_browse_wd.setText(QtGui.QApplication.translate("occamgui2D", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_browse_wd.setText(QtGui.QApplication.translate("occamgui2D", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("occamgui2D", "OCCAM executable", None, QtGui.QApplication.UnicodeUTF8))
        self.button_browse_occam.setText(QtGui.QApplication.translate("occamgui2D", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_browse_occam.setText(QtGui.QApplication.translate("occamgui2D", "/data/software/occam/bin/Occam2D", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("occamgui2D", "Make2DModel executable", None, QtGui.QApplication.UnicodeUTF8))
        self.button_browse_makemodel.setText(QtGui.QApplication.translate("occamgui2D", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_browse_makemodel.setText(QtGui.QApplication.translate("occamgui2D", "/data/gui/bin/MakeModel2Dmt_linux32bit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("occamgui2D", "EDI files folder", None, QtGui.QApplication.UnicodeUTF8))
        self.button_browse_edis.setText(QtGui.QApplication.translate("occamgui2D", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_browse_edis.setText(QtGui.QApplication.translate("occamgui2D", "/data/edi/jake", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_usestationlist.setText(QtGui.QApplication.translate("occamgui2D", "use station list file", None, QtGui.QApplication.UnicodeUTF8))
        self.button_browse_stations.setText(QtGui.QApplication.translate("occamgui2D", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_usedatafile.setText(QtGui.QApplication.translate("occamgui2D", "use existing data file", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_loaddatafile.setText(QtGui.QApplication.translate("occamgui2D", "Load data file", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("occamgui2D", "Choose a data file name", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_browse_datafilename.setText(QtGui.QApplication.translate("occamgui2D", "test.dat", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("occamgui2D", "Model name", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_modelname.setText(QtGui.QApplication.translate("occamgui2D", "test1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("occamgui2D", "Mode(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_mode.setItemText(0, QtGui.QApplication.translate("occamgui2D", "TM + TE", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_mode.setItemText(1, QtGui.QApplication.translate("occamgui2D", "TM", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_mode.setItemText(2, QtGui.QApplication.translate("occamgui2D", "TE", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("occamgui2D", "Frequency steps", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("occamgui2D", "Strike angle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("occamgui2D", "(West: 90 / East: -90)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("occamgui2D", "Profile orientation:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_alignment.setItemText(0, QtGui.QApplication.translate("occamgui2D", "NS", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_alignment.setItemText(1, QtGui.QApplication.translate("occamgui2D", "EW", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("occamgui2D", "trigger point for amalgamating blocks", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("occamgui2D", "Iteration steps", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("occamgui2D", "Target RMS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("occamgui2D", "Number of model layers", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("occamgui2D", "thickness of first layer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("occamgui2D", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("occamgui2D", "maximum block width ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("occamgui2D", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("occamgui2D", "layers per decade", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("occamgui2D", "Ohm m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("occamgui2D", "Resistivity (homogeneous half space -- starting model)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("occamgui2D", "Tipper Error", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_usetipper.setText(QtGui.QApplication.translate("occamgui2D", "Include Tipper", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_checkparameter.setText(QtGui.QApplication.translate("occamgui2D", "Check parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_runoccam.setText(QtGui.QApplication.translate("occamgui2D", "Run OCCAM 2D", None, QtGui.QApplication.UnicodeUTF8))

